/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param badgeUrl 
 * @param description 
 * @param id 
 * @param points 
 * @param rarityPercent 
 * @param title 
 * @param type 
 */
@Serializable

data class Achievement (

    @SerialName(value = "badgeUrl") @Required val badgeUrl: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.Long,

    @SerialName(value = "points") @Required val points: kotlin.Long,

    @SerialName(value = "rarityPercent") @Required val rarityPercent: kotlin.Double,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

