/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param count 
 * @param hops 
 * @param originFingerprint 
 * @param serverName 
 * @param username 
 */
@Serializable

data class AchievementEntry (

    @SerialName(value = "count") @Required val count: kotlin.Long,

    @SerialName(value = "hops") @Required val hops: kotlin.Long,

    @SerialName(value = "originFingerprint") @Required val originFingerprint: kotlin.String,

    @SerialName(value = "serverName") @Required val serverName: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String

) {


}

