/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avgCompletion 
 * @param game 
 * @param playersAttempted 
 * @param playersCompleted 
 * @param totalAchievements 
 */
@Serializable

data class AchievementGameResponse (

    @SerialName(value = "avgCompletion") @Required val avgCompletion: kotlin.Double,

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "playersAttempted") @Required val playersAttempted: kotlin.Long,

    @SerialName(value = "playersCompleted") @Required val playersCompleted: kotlin.Long,

    @SerialName(value = "totalAchievements") @Required val totalAchievements: kotlin.Long

) {


}

