/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.RALeaderboardEntryResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param leaderboard 
 * @param raGameId 
 * @param totalAchievements 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class AchievementLeaderboardResponse (

    @SerialName(value = "leaderboard") @Required val leaderboard: kotlin.collections.List<RALeaderboardEntryResponse>?,

    @SerialName(value = "raGameId") @Required val raGameId: kotlin.Long,

    @SerialName(value = "totalAchievements") @Required val totalAchievements: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

