/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param challengeId 
 * @param challengeName 
 * @param collectionName 
 * @param durationMs 
 * @param rating 
 * @param saveName 
 * @param seconds 
 * @param sharedSessionName 
 */
@Serializable

data class ActivityEventMetadata (

    @SerialName(value = "challengeId") val challengeId: kotlin.Long? = null,

    @SerialName(value = "challengeName") val challengeName: kotlin.String? = null,

    @SerialName(value = "collectionName") val collectionName: kotlin.String? = null,

    @SerialName(value = "durationMs") val durationMs: kotlin.Long? = null,

    @SerialName(value = "rating") val rating: kotlin.Long? = null,

    @SerialName(value = "saveName") val saveName: kotlin.String? = null,

    @SerialName(value = "seconds") val seconds: kotlin.Long? = null,

    @SerialName(value = "sharedSessionName") val sharedSessionName: kotlin.String? = null

) {


}

