/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avatarUrl 
 * @param consoleName 
 * @param createdAt 
 * @param eventType 
 * @param gameCoverUrl 
 * @param gameId 
 * @param gameTitle 
 * @param id 
 * @param metadata 
 * @param userId 
 * @param username 
 */
@Serializable

data class ActivityEventResponse (

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "eventType") @Required val eventType: kotlin.String,

    @SerialName(value = "gameCoverUrl") @Required val gameCoverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    // Manually patched: server returns metadata as a JSON object (or null
    // for events that have no metadata, e.g. queued_play_later), but the
    // OpenAPI generator emits `kotlin.String` for `type: object,
    // additionalProperties: {}`. The generated default fails to deserialize
    // both branches (Unexpected JSON token: Expected beginning of the
    // string, but got `{`/`null`). Use a nullable JsonObject so both
    // null and object payloads round-trip.
    @SerialName(value = "metadata") val metadata: kotlinx.serialization.json.JsonObject? = null,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String

) : kotlin.collections.HashMap<String, kotlinx.serialization.json.JsonElement>() {


}

