/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param disabled 
 * @param email 
 * @param password 
 * @param pendingApproval 
 * @param role 
 */
@Serializable

data class AdminUpdateUserRequest (

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = null,

    @SerialName(value = "email") val email: kotlin.String? = null,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "pendingApproval") val pendingApproval: kotlin.Boolean? = null,

    @SerialName(value = "role") val role: kotlin.String? = null

) {


}

