/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param password New account password (8-72 characters).
 * @param username New account username (3-64 characters).
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param role 
 */
@Serializable

data class AdminCreateUserRequest (

    /* New account password (8-72 characters). */
    @SerialName(value = "password") @Required val password: kotlin.String,

    /* New account username (3-64 characters). */
    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "role") val role: kotlin.String? = null

) {


}

