/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoles 
 * @param games 
 * @param saves 
 * @param users 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class AdminStatsResponse (

    @SerialName(value = "consoles") @Required val consoles: kotlin.Long,

    @SerialName(value = "games") @Required val games: kotlin.Long,

    @SerialName(value = "saves") @Required val saves: kotlin.Long,

    @SerialName(value = "users") @Required val users: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

