/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param canImportGames 
 * @param disabled 
 * @param password 
 * @param pendingApproval 
 * @param role 
 */
@Serializable

data class AdminUpdateUserRequest (

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "canImportGames") val canImportGames: kotlin.Boolean? = null,

    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = null,

    @SerialName(value = "password") val password: kotlin.String? = null,

    @SerialName(value = "pendingApproval") val pendingApproval: kotlin.Boolean? = null,

    @SerialName(value = "role") val role: kotlin.String? = null

) {


}

