/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.StatEntry

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param key 
 * @param label 
 * @param metric 
 * @param sources 
 * @param totalPlayTimeSeconds 
 * @param totalPlayers 
 */
@Serializable

data class AggregatedStat (

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "label") @Required val label: kotlin.String,

    @SerialName(value = "metric") @Required val metric: kotlin.String,

    @SerialName(value = "sources") @Required val sources: kotlin.collections.List<StatEntry>,

    @SerialName(value = "totalPlayTimeSeconds") @Required val totalPlayTimeSeconds: kotlin.Long,

    @SerialName(value = "totalPlayers") @Required val totalPlayers: kotlin.Long

) {


}

