/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param completionPercent 
 * @param game 
 * @param totalCount 
 * @param unlockedCount 
 */
@Serializable

data class AlmostDoneGame (

    @SerialName(value = "completionPercent") @Required val completionPercent: kotlin.Double,

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Long,

    @SerialName(value = "unlockedCount") @Required val unlockedCount: kotlin.Long

) {


}

