/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param game 
 * @param playedAt 
 * @param yearsAgo 
 */
@Serializable

data class AnniversaryItem (

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "playedAt") @Required val playedAt: kotlinx.datetime.Instant,

    @SerialName(value = "yearsAgo") @Required val yearsAgo: kotlin.Long

) {


}

