/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.ArtworkItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artworks 
 * @param page 
 * @param totalCount 
 * @param totalPages 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ArtworkGalleryResponse (

    @SerialName(value = "artworks") @Required val artworks: kotlin.collections.List<ArtworkItem>?,

    @SerialName(value = "page") @Required val page: kotlin.Long,

    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Long,

    @SerialName(value = "totalPages") @Required val totalPages: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

