/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.UserResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param user 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class AuthLoginResponse (

    @SerialName(value = "accessToken") @Required val accessToken: kotlin.String,

    @SerialName(value = "refreshToken") @Required val refreshToken: kotlin.String,

    @SerialName(value = "user") @Required val user: UserResponse,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

