/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artworkDownloaded 
 * @param companyDownloaded 
 * @param errors 
 * @param galleryDownloaded 
 * @param similarDownloaded 
 * @param topRatedDownloaded 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class BackfillImagesResponse (

    @SerialName(value = "artworkDownloaded") @Required val artworkDownloaded: kotlin.Long,

    @SerialName(value = "companyDownloaded") @Required val companyDownloaded: kotlin.Long,

    @SerialName(value = "errors") @Required val errors: kotlin.Long,

    @SerialName(value = "galleryDownloaded") @Required val galleryDownloaded: kotlin.Long,

    @SerialName(value = "similarDownloaded") @Required val similarDownloaded: kotlin.Long,

    @SerialName(value = "topRatedDownloaded") @Required val topRatedDownloaded: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

