/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleId 
 * @param md5 
 * @param name 
 * @param required 
 * @param propertySize 
 * @param status 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param consoleName 
 * @param description 
 * @param expectedMd5 
 * @param subDir 
 */
@Serializable

data class BiosFileResponse (

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String?,

    @SerialName(value = "md5") @Required val md5: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "required") @Required val required: kotlin.Boolean,

    @SerialName(value = "size") @Required val propertySize: kotlin.Long,

    @SerialName(value = "status") @Required val status: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "consoleName") val consoleName: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "expectedMd5") val expectedMd5: kotlin.String? = null,

    @SerialName(value = "subDir") val subDir: kotlin.String? = null

) {


}

