/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.BiosFileResponse
import com.spela.client.models.ConsoleBiosStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoles 
 * @param files 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class BiosListResponse (

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<ConsoleBiosStatus>,

    @SerialName(value = "files") @Required val files: kotlin.collections.List<BiosFileResponse>,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

