/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attemptCount 
 * @param completionCount 
 * @param consoleName 
 * @param coreName 
 * @param createdAt 
 * @param creatorAvatar 
 * @param creatorId 
 * @param creatorUsername 
 * @param description 
 * @param difficulty 
 * @param expiresAt 
 * @param gameCoverUrl 
 * @param gameId 
 * @param gameTitle 
 * @param id 
 * @param name 
 * @param saveFileSize 
 * @param screenshotUrl 
 * @param status 
 * @param type 
 * @param updatedAt 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ChallengeResponse (

    @SerialName(value = "attemptCount") @Required val attemptCount: kotlin.Long,

    @SerialName(value = "completionCount") @Required val completionCount: kotlin.Long,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coreName") @Required val coreName: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "creatorAvatar") @Required val creatorAvatar: kotlin.String,

    @SerialName(value = "creatorId") @Required val creatorId: kotlin.String,

    @SerialName(value = "creatorUsername") @Required val creatorUsername: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "difficulty") @Required val difficulty: kotlin.String,

    @SerialName(value = "expiresAt") @Required val expiresAt: kotlin.time.Instant?,

    @SerialName(value = "gameCoverUrl") @Required val gameCoverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "saveFileSize") @Required val saveFileSize: kotlin.Long,

    @SerialName(value = "screenshotUrl") @Required val screenshotUrl: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

