/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avatarUrl 
 * @param challengeId 
 * @param completedAt 
 * @param durationMs 
 * @param id 
 * @param isBest 
 * @param startedAt 
 * @param status 
 * @param userId 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ChallengeAttemptResponse (

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String,

    @SerialName(value = "challengeId") @Required val challengeId: kotlin.String,

    @SerialName(value = "completedAt") @Required val completedAt: kotlin.time.Instant?,

    @SerialName(value = "durationMs") @Required val durationMs: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "isBest") @Required val isBest: kotlin.Boolean,

    @SerialName(value = "startedAt") @Required val startedAt: kotlin.time.Instant,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

