/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param currentPassword Current password, required to authenticate the change.
 * @param newPassword New password (8-72 characters).
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ChangePasswordRequest (

    /* Current password, required to authenticate the change. */
    @SerialName(value = "currentPassword") @Required val currentPassword: kotlin.String,

    /* New password (8-72 characters). */
    @SerialName(value = "newPassword") @Required val newPassword: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

