/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gamesWithCheats 
 * @param totalCheats 
 * @param totalGames 
 * @param verifiedGames 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class CheatStatsResponse (

    @SerialName(value = "gamesWithCheats") @Required val gamesWithCheats: kotlin.Long,

    @SerialName(value = "totalCheats") @Required val totalCheats: kotlin.Long,

    @SerialName(value = "totalGames") @Required val totalGames: kotlin.Long,

    @SerialName(value = "verifiedGames") @Required val verifiedGames: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

