/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param gameCount 
 * @param id 
 * @param isPublic 
 * @param name 
 * @param updatedAt 
 * @param userId 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param avatarUrl 
 * @param coverUrl 
 * @param description 
 */
@Serializable

data class CollectionResponse (

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "isPublic") @Required val isPublic: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "avatarUrl") val avatarUrl: kotlin.String? = null,

    @SerialName(value = "coverUrl") val coverUrl: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

