/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param country 
 * @param description 
 * @param foundedYear 
 * @param logoUrl 
 * @param websiteUrl 
 * @param wikipediaUrl 
 */
@Serializable

data class CompanyInfo (

    @SerialName(value = "country") val country: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "foundedYear") val foundedYear: kotlin.Long? = null,

    @SerialName(value = "logoUrl") val logoUrl: kotlin.String? = null,

    @SerialName(value = "websiteUrl") val websiteUrl: kotlin.String? = null,

    @SerialName(value = "wikipediaUrl") val wikipediaUrl: kotlin.String? = null

) {


}

