/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param country 
 * @param description 
 * @param foundedYear 
 * @param logoUrl 
 * @param websiteUrl 
 * @param wikipediaUrl 
 */
@Serializable

data class CompanyInfo (

    @SerialName(value = "country") @Required val country: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "foundedYear") @Required val foundedYear: kotlin.Long,

    @SerialName(value = "logoUrl") @Required val logoUrl: kotlin.String,

    @SerialName(value = "websiteUrl") @Required val websiteUrl: kotlin.String,

    @SerialName(value = "wikipediaUrl") @Required val wikipediaUrl: kotlin.String

) {


}

