/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.CompletionistConsole

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoles 
 * @param overallPct 
 * @param totalGames 
 * @param totalPlayed 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class CompletionistMapResponse (

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<CompletionistConsole>?,

    @SerialName(value = "overallPct") @Required val overallPct: kotlin.Long,

    @SerialName(value = "totalGames") @Required val totalGames: kotlin.Long,

    @SerialName(value = "totalPlayed") @Required val totalPlayed: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

