/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param fileName 
 * @param md5 
 * @param required 
 * @param status 
 * @param subDir 
 */
@Serializable

data class ConsoleFileStatus (

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "fileName") @Required val fileName: kotlin.String,

    @SerialName(value = "md5") @Required val md5: kotlin.String,

    @SerialName(value = "required") @Required val required: kotlin.Boolean,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "subDir") val subDir: kotlin.String? = null

) {


}

