/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.ConsoleFileStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param biosRequired 
 * @param consoleId 
 * @param consoleName 
 * @param files 
 * @param optionalPresent 
 * @param optionalTotal 
 * @param requiredPresent 
 * @param requiredTotal 
 * @param status 
 */
@Serializable

data class ConsoleBiosStatus (

    @SerialName(value = "biosRequired") @Required val biosRequired: kotlin.Boolean,

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "files") @Required val files: kotlin.collections.List<ConsoleFileStatus>?,

    @SerialName(value = "optionalPresent") @Required val optionalPresent: kotlin.Long,

    @SerialName(value = "optionalTotal") @Required val optionalTotal: kotlin.Long,

    @SerialName(value = "requiredPresent") @Required val requiredPresent: kotlin.Long,

    @SerialName(value = "requiredTotal") @Required val requiredTotal: kotlin.Long,

    @SerialName(value = "status") @Required val status: kotlin.String

) {


}

