/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.HardwareMakerResponse
import com.spela.client.models.MediaTypeResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param abbreviation 
 * @param browserPlayable 
 * @param code 
 * @param colorTheme 
 * @param coverAspectRatio 
 * @param createdAt 
 * @param defaultCore 
 * @param emulatorJsCore 
 * @param extensions 
 * @param gameCount 
 * @param generation 
 * @param iconUrl 
 * @param id 
 * @param logoPngUrl 
 * @param logoUrl 
 * @param maker 
 * @param mediaType 
 * @param name 
 * @param playable 
 * @param releaseYear 
 * @param saveStateSupport 
 * @param summary 
 * @param unitsSold 
 * @param updatedAt 
 */
@Serializable

data class ConsoleResponse (

    @SerialName(value = "abbreviation") @Required val abbreviation: kotlin.String,

    @SerialName(value = "browserPlayable") @Required val browserPlayable: kotlin.Boolean,

    @SerialName(value = "code") @Required val code: kotlin.String,

    @SerialName(value = "colorTheme") @Required val colorTheme: kotlin.String,

    @SerialName(value = "coverAspectRatio") @Required val coverAspectRatio: kotlin.Double,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "defaultCore") @Required val defaultCore: kotlin.String,

    @SerialName(value = "emulatorJsCore") @Required val emulatorJsCore: kotlin.String,

    @SerialName(value = "extensions") @Required val extensions: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "generation") @Required val generation: kotlin.Long,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "logoPngUrl") @Required val logoPngUrl: kotlin.String,

    @SerialName(value = "logoUrl") @Required val logoUrl: kotlin.String,

    @SerialName(value = "maker") @Required val maker: HardwareMakerResponse,

    @SerialName(value = "mediaType") @Required val mediaType: MediaTypeResponse,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "playable") @Required val playable: kotlin.Boolean,

    @SerialName(value = "releaseYear") @Required val releaseYear: kotlin.Long?,

    @SerialName(value = "saveStateSupport") @Required val saveStateSupport: kotlin.Boolean,

    @SerialName(value = "summary") @Required val summary: kotlin.String?,

    @SerialName(value = "unitsSold") @Required val unitsSold: kotlin.Long?,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant

) {


}

