/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.ConsoleResponse
import com.spela.client.models.DeveloperSummary
import com.spela.client.models.GameResponse
import com.spela.client.models.GenreCount

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param console 
 * @param essentials 
 * @param genreBreakdown 
 * @param hiddenGems 
 * @param recentlyAdded 
 * @param recentlyPlayed 
 * @param topDevelopers 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ConsoleShowcaseResponse (

    @SerialName(value = "console") @Required val console: ConsoleResponse,

    @SerialName(value = "essentials") @Required val essentials: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "genreBreakdown") @Required val genreBreakdown: kotlin.collections.List<GenreCount>?,

    @SerialName(value = "hiddenGems") @Required val hiddenGems: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "recentlyAdded") @Required val recentlyAdded: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "recentlyPlayed") @Required val recentlyPlayed: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "topDevelopers") @Required val topDevelopers: kotlin.collections.List<DeveloperSummary>?,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

