/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param description 
 * @param displayName 
 * @param downloadUrl 
 * @param id 
 * @param name 
 * @param platforms 
 * @param updatedAt 
 * @param version 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class Core (

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    @SerialName(value = "downloadUrl") @Required val downloadUrl: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.Long,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "platforms") @Required val platforms: kotlin.String,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "version") @Required val version: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

