/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param fetchedAt When the server last downloaded (or re-hashed) this core. Null if it has never been fetched.
 * @param sha256 Hex sha256 of the cached binary on the server. Empty if the server hasn't served this core yet.
 * @param sizeBytes Byte length of the cached binary. 0 when no binary has been fetched yet.
 * @param sourceUrl URL the server pulled this binary from. Empty when the server is still defaulting to the buildbot nightly endpoint.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class CoreManifestResponse (

    /* When the server last downloaded (or re-hashed) this core. Null if it has never been fetched. */
    @SerialName(value = "fetchedAt") @Required val fetchedAt: kotlinx.datetime.Instant?,

    /* Hex sha256 of the cached binary on the server. Empty if the server hasn't served this core yet. */
    @SerialName(value = "sha256") @Required val sha256: kotlin.String,

    /* Byte length of the cached binary. 0 when no binary has been fetched yet. */
    @SerialName(value = "sizeBytes") @Required val sizeBytes: kotlin.Long,

    /* URL the server pulled this binary from. Empty when the server is still defaulting to the buildbot nightly endpoint. */
    @SerialName(value = "sourceUrl") @Required val sourceUrl: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

