/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param label 
 * @param libretroName 
 * @param source 
 * @param url 
 */
@Serializable

data class CoverOption (

    @SerialName(value = "label") @Required val label: kotlin.String,

    @SerialName(value = "libretroName") @Required val libretroName: kotlin.String,

    @SerialName(value = "source") @Required val source: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String

) {


}

