/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.CoverItem

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param covers 
 * @param page 
 * @param totalCount 
 * @param totalPages 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class CoverGalleryResponse (

    @SerialName(value = "covers") @Required val covers: kotlin.collections.List<CoverItem>?,

    @SerialName(value = "page") @Required val page: kotlin.Long,

    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Long,

    @SerialName(value = "totalPages") @Required val totalPages: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

