/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleAbbreviation 
 * @param consoleColor 
 * @param consoleName 
 * @param coverAspectRatio 
 * @param coverUrl 
 * @param gameId 
 * @param gameTitle 
 * @param igdbCriticsRating 
 */
@Serializable

data class CoverItem (

    @SerialName(value = "consoleAbbreviation") @Required val consoleAbbreviation: kotlin.String,

    @SerialName(value = "consoleColor") @Required val consoleColor: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverAspectRatio") @Required val coverAspectRatio: kotlin.Double,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "igdbCriticsRating") @Required val igdbCriticsRating: kotlin.Double

) {


}

