/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param coreName 
 * @param gameId 
 * @param inputDelay 
 */
@Serializable

data class CreateNetplaySessionRequest (

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "coreName") val coreName: kotlin.String? = null,

    @SerialName(value = "gameId") val gameId: kotlin.String? = null,

    @SerialName(value = "inputDelay") val inputDelay: kotlin.Long? = null

) {


}

