/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param communityRating 
 * @param game 
 * @param igdbCriticsRating 
 * @param ratingCount 
 */
@Serializable

data class CultClassicGame (

    @SerialName(value = "communityRating") @Required val communityRating: kotlin.Double,

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "igdbCriticsRating") @Required val igdbCriticsRating: kotlin.Double,

    @SerialName(value = "ratingCount") @Required val ratingCount: kotlin.Long

) {


}

