/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param disabled 
 * @param id 
 * @param role 
 * @param username 
 */
@Serializable

data class DeletedUserResponse (

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "deletedAt") @Required val deletedAt: kotlinx.datetime.Instant,

    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "role") @Required val role: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String

) {


}

