/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avgRating 
 * @param consoles 
 * @param gameCount 
 * @param heroUrl 
 * @param name 
 * @param topGames 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class DeveloperSpotlightResponse (

    @SerialName(value = "avgRating") @Required val avgRating: kotlin.Double,

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "heroUrl") @Required val heroUrl: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "topGames") @Required val topGames: kotlin.collections.List<GameResponse>?,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

