/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.ActiveYears
import com.spela.client.models.CompanyInfo
import com.spela.client.models.EntityUserStats
import com.spela.client.models.GameResponse
import com.spela.client.models.GenreCount
import com.spela.client.models.NameCount
import com.spela.client.models.PlatformCount
import com.spela.client.models.RatingDistribution
import com.spela.client.models.RelatedDeveloper
import com.spela.client.models.TimelineEntry

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avgRating 
 * @param consoles 
 * @param gameCount 
 * @param games 
 * @param genreBreakdown 
 * @param name 
 * @param platformBreakdown 
 * @param publishers 
 * @param ratingDistribution 
 * @param topGames 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param activeYears 
 * @param companyInfo 
 * @param heroUrl 
 * @param primaryGenre 
 * @param relatedDevelopers 
 * @param timeline 
 * @param userStats 
 */
@Serializable

data class DeveloperDetailResponse (

    @SerialName(value = "avgRating") @Required val avgRating: kotlin.Double,

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "games") @Required val games: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "genreBreakdown") @Required val genreBreakdown: kotlin.collections.List<GenreCount>?,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "platformBreakdown") @Required val platformBreakdown: kotlin.collections.List<PlatformCount>?,

    @SerialName(value = "publishers") @Required val publishers: kotlin.collections.List<NameCount>?,

    @SerialName(value = "ratingDistribution") @Required val ratingDistribution: RatingDistribution,

    @SerialName(value = "topGames") @Required val topGames: kotlin.collections.List<GameResponse>?,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "activeYears") val activeYears: ActiveYears? = null,

    @SerialName(value = "companyInfo") val companyInfo: CompanyInfo? = null,

    @SerialName(value = "heroUrl") val heroUrl: kotlin.String? = null,

    @SerialName(value = "primaryGenre") val primaryGenre: kotlin.String? = null,

    @SerialName(value = "relatedDevelopers") val relatedDevelopers: kotlin.collections.List<RelatedDeveloper>? = null,

    @SerialName(value = "timeline") val timeline: kotlin.collections.List<TimelineEntry>? = null,

    @SerialName(value = "userStats") val userStats: EntityUserStats? = null

) {


}

