/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param discNumber 
 * @param fileName 
 * @param fileSize 
 */
@Serializable

data class DiscResponse (

    @SerialName(value = "discNumber") @Required val discNumber: kotlin.Long,

    @SerialName(value = "fileName") @Required val fileName: kotlin.String,

    @SerialName(value = "fileSize") @Required val fileSize: kotlin.Long

) {


}

