/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param current 
 * @param failures 
 * @param gameName 
 * @param successes 
 * @param total 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class EnrichmentStatusResponse (

    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    @SerialName(value = "current") @Required val current: kotlin.Long,

    @SerialName(value = "failures") @Required val failures: kotlin.Long,

    @SerialName(value = "gameName") @Required val gameName: kotlin.String,

    @SerialName(value = "successes") @Required val successes: kotlin.Long,

    @SerialName(value = "total") @Required val total: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

