/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param favoriteCount 
 * @param gamesPlayed 
 * @param totalPlayTime 
 * @param mostPlayedGame 
 */
@Serializable

data class EntityUserStats (

    @SerialName(value = "favoriteCount") @Required val favoriteCount: kotlin.Long,

    @SerialName(value = "gamesPlayed") @Required val gamesPlayed: kotlin.Long,

    @SerialName(value = "totalPlayTime") @Required val totalPlayTime: kotlin.Long,

    @SerialName(value = "mostPlayedGame") val mostPlayedGame: GameResponse? = null

) {


}

