/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param earned 
 * @param icon 
 * @param id 
 * @param name 
 * @param progress 
 * @param target 
 */
@Serializable

data class ExplorerBadge (

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "earned") @Required val earned: kotlin.Boolean,

    @SerialName(value = "icon") @Required val icon: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "progress") @Required val progress: kotlin.Long,

    @SerialName(value = "target") @Required val target: kotlin.Long

) {


}

