/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param attemptCount 
 * @param completionCount 
 * @param createdAt 
 * @param creatorUsername 
 * @param difficulty 
 * @param gameId 
 * @param gameTitle 
 * @param id 
 * @param name 
 * @param type 
 * @param consoleName 
 * @param description 
 * @param expiresAt 
 * @param gameCoverUrl 
 */
@Serializable

data class ExploreChallengeResponse (

    @SerialName(value = "attemptCount") @Required val attemptCount: kotlin.Long,

    @SerialName(value = "completionCount") @Required val completionCount: kotlin.Long,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "creatorUsername") @Required val creatorUsername: kotlin.String,

    @SerialName(value = "difficulty") @Required val difficulty: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "consoleName") val consoleName: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "expiresAt") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "gameCoverUrl") val gameCoverUrl: kotlin.String? = null

) {


}

