/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleAbbreviation 
 * @param consoleColor 
 * @param consoleId 
 * @param consoleName 
 * @param gameId 
 * @param genre 
 * @param heroUrl 
 * @param igdbCriticsRating 
 * @param isFavorite 
 * @param isPlayLater 
 * @param logoUrl 
 * @param title 
 */
@Serializable

data class FeaturedGameResponse (

    @SerialName(value = "consoleAbbreviation") @Required val consoleAbbreviation: kotlin.String,

    @SerialName(value = "consoleColor") @Required val consoleColor: kotlin.String,

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "genre") @Required val genre: kotlin.String,

    @SerialName(value = "heroUrl") @Required val heroUrl: kotlin.String,

    @SerialName(value = "igdbCriticsRating") @Required val igdbCriticsRating: kotlin.Double,

    @SerialName(value = "isFavorite") @Required val isFavorite: kotlin.Boolean,

    @SerialName(value = "isPlayLater") @Required val isPlayLater: kotlin.Boolean,

    @SerialName(value = "logoUrl") @Required val logoUrl: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String

) {


}

