/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bytes 
 * @param createdAt 
 * @param dataClass 
 * @param direction 
 * @param durationMs 
 * @param error 
 * @param finishedAt 
 * @param httpStatus 
 * @param id 
 * @param itemCount 
 * @param maxHops 
 * @param operation 
 * @param peerFingerprint 
 * @param peerName 
 * @param requestId 
 * @param startedAt 
 * @param status 
 */
@Serializable

data class FederationExchange (

    @SerialName(value = "bytes") @Required val bytes: kotlin.Long,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "dataClass") @Required val dataClass: kotlin.String,

    @SerialName(value = "direction") @Required val direction: kotlin.String,

    @SerialName(value = "durationMs") @Required val durationMs: kotlin.Long,

    @SerialName(value = "error") @Required val error: kotlin.String,

    @SerialName(value = "finishedAt") @Required val finishedAt: kotlinx.datetime.Instant,

    @SerialName(value = "httpStatus") @Required val httpStatus: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.Long,

    @SerialName(value = "itemCount") @Required val itemCount: kotlin.Long,

    @SerialName(value = "maxHops") @Required val maxHops: kotlin.Long,

    @SerialName(value = "operation") @Required val operation: kotlin.String,

    @SerialName(value = "peerFingerprint") @Required val peerFingerprint: kotlin.String,

    @SerialName(value = "peerName") @Required val peerName: kotlin.String,

    @SerialName(value = "requestId") @Required val requestId: kotlin.String,

    @SerialName(value = "startedAt") @Required val startedAt: kotlinx.datetime.Instant,

    @SerialName(value = "status") @Required val status: kotlin.String

) {


}

