/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param games 
 * @param title 
 * @param type 
 * @param genre 
 * @param sourceGame 
 */
@Serializable

data class ForYouRowResponse (

    @SerialName(value = "games") @Required val games: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "genre") val genre: kotlin.String? = null,

    @SerialName(value = "sourceGame") val sourceGame: GameResponse? = null

) {


}

