/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param game 
 * @param totalAchievements 
 * @param totalPoints 
 */
@Serializable

data class FreshChallengeGame (

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "totalAchievements") @Required val totalAchievements: kotlin.Long,

    @SerialName(value = "totalPoints") @Required val totalPoints: kotlin.Long

) {


}

