/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param gameId 
 * @param id 
 * @param rating 
 * @param updatedAt 
 * @param userId 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param avatarUrl 
 * @param review 
 */
@Serializable

data class GameRatingResponse (

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "rating") @Required val rating: kotlin.Long,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "avatarUrl") val avatarUrl: kotlin.String? = null,

    @SerialName(value = "review") val review: kotlin.String? = null

) {


}

