/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.Achievement

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param achievements Achievement definitions for this game (empty when unknown).
 * @param raGameId RetroAchievements game ID (0 when unknown).
 * @param status Only set to 'pending' when the data is being fetched asynchronously; clients should retry.
 * @param title RetroAchievements game title; present when achievement data is available.
 * @param totalCount Total number of achievements for this game.
 * @param totalPoints Total number of points available across all achievements.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class GameAchievementsResponse (

    /* Achievement definitions for this game (empty when unknown). */
    @SerialName(value = "achievements") @Required val achievements: kotlin.collections.List<Achievement>,

    /* RetroAchievements game ID (0 when unknown). */
    @SerialName(value = "raGameId") @Required val raGameId: kotlin.Long,

    /* Only set to 'pending' when the data is being fetched asynchronously; clients should retry. */
    @SerialName(value = "status") @Required val status: GameAchievementsResponse.Status,

    /* RetroAchievements game title; present when achievement data is available. */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* Total number of achievements for this game. */
    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Long,

    /* Total number of points available across all achievements. */
    @SerialName(value = "totalPoints") @Required val totalPoints: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {

    /**
     * Only set to 'pending' when the data is being fetched asynchronously; clients should retry.
     *
     * Values: pending
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending");
    }

}

