/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cheatsEnabled 
 * @param coreName 
 * @param createdAt 
 * @param gameId 
 * @param id 
 * @param isSharedSession 
 * @param lastPlayedAt 
 * @param lastPlayedBy 
 * @param lastPlayedByUsername 
 * @param memberAvatars 
 * @param memberCount 
 * @param memberUsernames 
 * @param name 
 * @param ownerId 
 * @param ownerUsername 
 * @param pinnedCoreSha256 
 * @param saveCount 
 * @param screenshotUrl 
 * @param sharedSessionId 
 * @param totalPlayTime 
 * @param updatedAt 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class GameSessionResponse (

    @SerialName(value = "cheatsEnabled") @Required val cheatsEnabled: kotlin.Boolean,

    @SerialName(value = "coreName") @Required val coreName: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "isSharedSession") @Required val isSharedSession: kotlin.Boolean,

    @SerialName(value = "lastPlayedAt") @Required val lastPlayedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "lastPlayedBy") @Required val lastPlayedBy: kotlin.String?,

    @SerialName(value = "lastPlayedByUsername") @Required val lastPlayedByUsername: kotlin.String?,

    @SerialName(value = "memberAvatars") @Required val memberAvatars: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "memberCount") @Required val memberCount: kotlin.Long,

    @SerialName(value = "memberUsernames") @Required val memberUsernames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "ownerId") @Required val ownerId: kotlin.String,

    @SerialName(value = "ownerUsername") @Required val ownerUsername: kotlin.String,

    @SerialName(value = "pinnedCoreSha256") @Required val pinnedCoreSha256: kotlin.String,

    @SerialName(value = "saveCount") @Required val saveCount: kotlin.Long,

    @SerialName(value = "screenshotUrl") @Required val screenshotUrl: kotlin.String,

    @SerialName(value = "sharedSessionId") @Required val sharedSessionId: kotlin.String?,

    @SerialName(value = "totalPlayTime") @Required val totalPlayTime: kotlin.Long,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

