/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gridUrl 
 * @param heroUrl 
 * @param iconUrl 
 * @param logoUrl 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class GameArtworkResponse (

    @SerialName(value = "gridUrl") @Required val gridUrl: kotlin.String,

    @SerialName(value = "heroUrl") @Required val heroUrl: kotlin.String,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String,

    @SerialName(value = "logoUrl") @Required val logoUrl: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

