/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param libraryGames 
 * @param name 
 * @param totalGames 
 */
@Serializable

data class GameFranchiseResponse (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "libraryGames") @Required val libraryGames: kotlin.Long,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "totalGames") @Required val totalGames: kotlin.Long

) {


}

