/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status Service status: 'ok' or 'degraded'.
 * @param version Build version string.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class HealthResponse (

    /* Service status: 'ok' or 'degraded'. */
    @SerialName(value = "status") @Required val status: HealthResponse.Status,

    /* Build version string. */
    @SerialName(value = "version") @Required val version: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {

    /**
     * Service status: 'ok' or 'degraded'.
     *
     * Values: ok,degraded
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ok") ok("ok"),
        @SerialName(value = "degraded") degraded("degraded");
    }

}

