/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cheatsImported 
 * @param failed 
 * @param gamesImported 
 * @param skipped 
 * @param totalGames 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ImportResult (

    @SerialName(value = "cheatsImported") @Required val cheatsImported: kotlin.Long,

    @SerialName(value = "failed") @Required val failed: kotlin.Long,

    @SerialName(value = "gamesImported") @Required val gamesImported: kotlin.Long,

    @SerialName(value = "skipped") @Required val skipped: kotlin.Long,

    @SerialName(value = "totalGames") @Required val totalGames: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

