/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bytesDownloaded 
 * @param completedAt 
 * @param console 
 * @param createdAt 
 * @param errorMessage 
 * @param gameId 
 * @param id 
 * @param key 
 * @param requestedByUserId 
 * @param startedAt 
 * @param status 
 * @param title 
 * @param totalBytes 
 * @param updatedAt 
 */
@Serializable

data class ImportJob (

    @SerialName(value = "bytesDownloaded") @Required val bytesDownloaded: kotlin.Long,

    @SerialName(value = "completedAt") @Required val completedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "console") @Required val console: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "errorMessage") @Required val errorMessage: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.Long?,

    @SerialName(value = "id") @Required val id: kotlin.Long,

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "requestedByUserId") @Required val requestedByUserId: kotlin.Long,

    @SerialName(value = "startedAt") @Required val startedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "totalBytes") @Required val totalBytes: kotlin.Long,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant

) {


}

