/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleId 
 * @param consoleName 
 * @param coverUrl 
 * @param gameId 
 * @param name 
 * @param rank 
 * @param timeToBeatCompletely 
 * @param timeToBeatHastily 
 * @param timeToBeatNormally 
 */
@Serializable

data class LongestGameResponse (

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "rank") @Required val rank: kotlin.Long,

    @SerialName(value = "timeToBeatCompletely") @Required val timeToBeatCompletely: kotlin.Long,

    @SerialName(value = "timeToBeatHastily") @Required val timeToBeatHastily: kotlin.Long,

    @SerialName(value = "timeToBeatNormally") @Required val timeToBeatNormally: kotlin.Long

) {


}

