/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param incomplete 
 * @param unscraped 
 * @param unverified 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class MetadataMatchesResponse (

    @SerialName(value = "incomplete") @Required val incomplete: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "unscraped") @Required val unscraped: kotlin.collections.List<GameResponse>?,

    @SerialName(value = "unverified") @Required val unverified: kotlin.collections.List<GameResponse>?,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

