/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientId 
 * @param coverAspectRatio 
 * @param createdAt 
 * @param gameId 
 * @param gameTitle 
 * @param hostId 
 * @param hostUsername 
 * @param id 
 * @param inputDelay 
 * @param inviteCode 
 * @param status 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param clientAvatarUrl 
 * @param clientUsername 
 * @param consoleId 
 * @param consoleName 
 * @param coreName 
 * @param endReason 
 * @param endedAt 
 * @param gameCoverUrl 
 * @param hostAvatarUrl 
 * @param startedAt 
 */
@Serializable

data class NetplaySessionResponse (

    @SerialName(value = "clientId") @Required val clientId: kotlin.String?,

    @SerialName(value = "coverAspectRatio") @Required val coverAspectRatio: kotlin.Double,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "hostId") @Required val hostId: kotlin.String,

    @SerialName(value = "hostUsername") @Required val hostUsername: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "inputDelay") @Required val inputDelay: kotlin.Long,

    @SerialName(value = "inviteCode") @Required val inviteCode: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "clientAvatarUrl") val clientAvatarUrl: kotlin.String? = null,

    @SerialName(value = "clientUsername") val clientUsername: kotlin.String? = null,

    @SerialName(value = "consoleId") val consoleId: kotlin.String? = null,

    @SerialName(value = "consoleName") val consoleName: kotlin.String? = null,

    @SerialName(value = "coreName") val coreName: kotlin.String? = null,

    @SerialName(value = "endReason") val endReason: kotlin.String? = null,

    @SerialName(value = "endedAt") val endedAt: kotlin.time.Instant? = null,

    @SerialName(value = "gameCoverUrl") val gameCoverUrl: kotlin.String? = null,

    @SerialName(value = "hostAvatarUrl") val hostAvatarUrl: kotlin.String? = null,

    @SerialName(value = "startedAt") val startedAt: kotlin.time.Instant? = null

) {


}

