/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientAvatarUrl 
 * @param clientId 
 * @param clientUsername 
 * @param consoleId 
 * @param consoleName 
 * @param coreName 
 * @param coverAspectRatio 
 * @param createdAt 
 * @param endReason 
 * @param endedAt 
 * @param gameCoverUrl 
 * @param gameId 
 * @param gameTitle 
 * @param hostAvatarUrl 
 * @param hostId 
 * @param hostUsername 
 * @param id 
 * @param inputDelay 
 * @param inviteCode 
 * @param startedAt 
 * @param status 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class NetplaySessionResponse (

    @SerialName(value = "clientAvatarUrl") @Required val clientAvatarUrl: kotlin.String,

    @SerialName(value = "clientId") @Required val clientId: kotlin.String?,

    @SerialName(value = "clientUsername") @Required val clientUsername: kotlin.String,

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coreName") @Required val coreName: kotlin.String,

    @SerialName(value = "coverAspectRatio") @Required val coverAspectRatio: kotlin.Double,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "endReason") @Required val endReason: kotlin.String,

    @SerialName(value = "endedAt") @Required val endedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "gameCoverUrl") @Required val gameCoverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "hostAvatarUrl") @Required val hostAvatarUrl: kotlin.String,

    @SerialName(value = "hostId") @Required val hostId: kotlin.String,

    @SerialName(value = "hostUsername") @Required val hostUsername: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "inputDelay") @Required val inputDelay: kotlin.Long,

    @SerialName(value = "inviteCode") @Required val inviteCode: kotlin.String,

    @SerialName(value = "startedAt") @Required val startedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "status") @Required val status: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

