/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param baseUrl 
 * @param fingerprint 
 * @param nonce 
 * @param publicKey 
 * @param sig 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class PairRequestBody (

    @SerialName(value = "baseUrl") @Required val baseUrl: kotlin.String,

    @SerialName(value = "fingerprint") @Required val fingerprint: kotlin.String,

    @SerialName(value = "nonce") @Required val nonce: kotlin.String,

    @SerialName(value = "publicKey") @Required val publicKey: kotlin.String,

    @SerialName(value = "sig") @Required val sig: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

