/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clockSkewSeconds 
 * @param error 
 * @param fingerprintMatch 
 * @param latencyMs 
 * @param peerFingerprint 
 * @param peerUnixTime 
 * @param reachable 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class PingResult (

    @SerialName(value = "clockSkewSeconds") @Required val clockSkewSeconds: kotlin.Long,

    @SerialName(value = "error") @Required val error: kotlin.String,

    @SerialName(value = "fingerprintMatch") @Required val fingerprintMatch: kotlin.Boolean,

    @SerialName(value = "latencyMs") @Required val latencyMs: kotlin.Long,

    @SerialName(value = "peerFingerprint") @Required val peerFingerprint: kotlin.String,

    @SerialName(value = "peerUnixTime") @Required val peerUnixTime: kotlin.Long,

    @SerialName(value = "reachable") @Required val reachable: kotlin.Boolean,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

