/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gameId 
 * @param lastPlayedAt 
 * @param playTime 
 */
@Serializable

data class PlayStatsEntry (

    @SerialName(value = "gameId") @Required val gameId: kotlin.Long,

    @SerialName(value = "lastPlayedAt") @Required val lastPlayedAt: kotlin.String,

    @SerialName(value = "playTime") @Required val playTime: kotlin.Long

) {


}

