/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gameKey 
 * @param gameTitle 
 * @param hops 
 * @param originFingerprint 
 * @param serverName 
 * @param username 
 */
@Serializable

data class PresenceEntry (

    @SerialName(value = "gameKey") @Required val gameKey: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "hops") @Required val hops: kotlin.Long,

    @SerialName(value = "originFingerprint") @Required val originFingerprint: kotlin.String,

    @SerialName(value = "serverName") @Required val serverName: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String

) {


}

