/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.OnlineUserGameResponse
import com.spela.client.models.PublicProfileGame

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param favoriteGames 
 * @param gamesPlayed 
 * @param id 
 * @param isOnline 
 * @param memberSince 
 * @param recentGames 
 * @param topGames 
 * @param totalPlayTime 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param avatarUrl 
 * @param currentGame 
 */
@Serializable

data class PublicProfileResponse (

    @SerialName(value = "favoriteGames") @Required val favoriteGames: kotlin.collections.List<PublicProfileGame>?,

    @SerialName(value = "gamesPlayed") @Required val gamesPlayed: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "isOnline") @Required val isOnline: kotlin.Boolean,

    @SerialName(value = "memberSince") @Required val memberSince: kotlin.time.Instant,

    @SerialName(value = "recentGames") @Required val recentGames: kotlin.collections.List<PublicProfileGame>?,

    @SerialName(value = "topGames") @Required val topGames: kotlin.collections.List<PublicProfileGame>?,

    @SerialName(value = "totalPlayTime") @Required val totalPlayTime: kotlin.Long,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "avatarUrl") val avatarUrl: kotlin.String? = null,

    @SerialName(value = "currentGame") val currentGame: OnlineUserGameResponse? = null

) {


}

