/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.ActiveYears
import com.spela.client.models.CompanyInfo
import com.spela.client.models.EntityUserStats
import com.spela.client.models.GameResponse
import com.spela.client.models.NameCount
import com.spela.client.models.PlatformCount
import com.spela.client.models.RatingDistribution
import com.spela.client.models.RelatedPublisher
import com.spela.client.models.TimelineEntry

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param activeYears 
 * @param avgRating 
 * @param companyInfo 
 * @param consoles 
 * @param developers 
 * @param gameCount 
 * @param games 
 * @param heroUrl 
 * @param name 
 * @param platformBreakdown 
 * @param primaryGenre 
 * @param ratingDistribution 
 * @param relatedPublishers 
 * @param timeline 
 * @param topGames 
 * @param userStats 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class PublisherDetailResponse (

    @SerialName(value = "activeYears") @Required val activeYears: ActiveYears,

    @SerialName(value = "avgRating") @Required val avgRating: kotlin.Double,

    @SerialName(value = "companyInfo") @Required val companyInfo: CompanyInfo,

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "developers") @Required val developers: kotlin.collections.List<NameCount>,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "games") @Required val games: kotlin.collections.List<GameResponse>,

    @SerialName(value = "heroUrl") @Required val heroUrl: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "platformBreakdown") @Required val platformBreakdown: kotlin.collections.List<PlatformCount>,

    @SerialName(value = "primaryGenre") @Required val primaryGenre: kotlin.String,

    @SerialName(value = "ratingDistribution") @Required val ratingDistribution: RatingDistribution,

    @SerialName(value = "relatedPublishers") @Required val relatedPublishers: kotlin.collections.List<RelatedPublisher>,

    @SerialName(value = "timeline") @Required val timeline: kotlin.collections.List<TimelineEntry>,

    @SerialName(value = "topGames") @Required val topGames: kotlin.collections.List<GameResponse>,

    @SerialName(value = "userStats") @Required val userStats: EntityUserStats,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

