/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleName 
 * @param coverUrl 
 * @param id 
 * @param playTime 
 * @param title 
 */
@Serializable

data class PublicProfileGame (

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "playTime") @Required val playTime: kotlin.Long,

    @SerialName(value = "title") @Required val title: kotlin.String

) {


}

