/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avatarUrl 
 * @param earnedPoints 
 * @param firstUnlockedAt 
 * @param isComplete 
 * @param lastUnlockedAt 
 * @param unlockedCount 
 * @param userId 
 * @param username 
 */
@Serializable

data class RALeaderboardEntryResponse (

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String,

    @SerialName(value = "earnedPoints") @Required val earnedPoints: kotlin.Long,

    @SerialName(value = "firstUnlockedAt") @Required val firstUnlockedAt: kotlinx.datetime.Instant,

    @SerialName(value = "isComplete") @Required val isComplete: kotlin.Boolean,

    @SerialName(value = "lastUnlockedAt") @Required val lastUnlockedAt: kotlinx.datetime.Instant,

    @SerialName(value = "unlockedCount") @Required val unlockedCount: kotlin.Long,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String

) {


}

