/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param achievementId 
 * @param isHardcore 
 * @param playTimeAtUnlock 
 * @param unlockedAt 
 */
@Serializable

data class RAProgressEntry (

    @SerialName(value = "achievementId") @Required val achievementId: kotlin.Long,

    @SerialName(value = "isHardcore") @Required val isHardcore: kotlin.Boolean,

    @SerialName(value = "playTimeAtUnlock") @Required val playTimeAtUnlock: kotlin.Long,

    @SerialName(value = "unlockedAt") @Required val unlockedAt: kotlin.String

) {


}

