/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param achievementRaId 
 * @param badgeUrl 
 * @param consoleName 
 * @param coverUrl 
 * @param description 
 * @param gameId 
 * @param gameTitle 
 * @param isHardcore 
 * @param playTimeAtUnlock 
 * @param points 
 * @param title 
 * @param unlockedAt 
 */
@Serializable

data class RARecentAchievementResponse (

    @SerialName(value = "achievementRaId") @Required val achievementRaId: kotlin.Long,

    @SerialName(value = "badgeUrl") @Required val badgeUrl: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "isHardcore") @Required val isHardcore: kotlin.Boolean,

    @SerialName(value = "playTimeAtUnlock") @Required val playTimeAtUnlock: kotlin.Long,

    @SerialName(value = "points") @Required val points: kotlin.Long,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "unlockedAt") @Required val unlockedAt: kotlin.time.Instant

) {


}

