/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param game 
 * @param rating 
 * @param review 
 * @param reviewedAt 
 * @param reviewerName 
 */
@Serializable

data class RecentReviewItem (

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "rating") @Required val rating: kotlin.Long,

    @SerialName(value = "review") @Required val review: kotlin.String,

    @SerialName(value = "reviewedAt") @Required val reviewedAt: kotlinx.datetime.Instant,

    @SerialName(value = "reviewerName") @Required val reviewerName: kotlin.String

) {


}

