/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param changed True when the on-disk sha256 differed from the previously persisted sha256.
 * @param fetchedAt Timestamp persisted on the row after this refresh.
 * @param oldSha256 The sha256 stored before this refresh. Empty on the first-ever fingerprint.
 * @param sha256 Sha256 of the on-disk binary after the refresh.
 * @param sizeBytes Size of the on-disk binary after the refresh.
 * @param sourceUrl Source URL persisted on the row. Empty for buildbot-default cores.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class RefreshCoreResponse (

    /* True when the on-disk sha256 differed from the previously persisted sha256. */
    @SerialName(value = "changed") @Required val changed: kotlin.Boolean,

    /* Timestamp persisted on the row after this refresh. */
    @SerialName(value = "fetchedAt") @Required val fetchedAt: kotlin.time.Instant?,

    /* The sha256 stored before this refresh. Empty on the first-ever fingerprint. */
    @SerialName(value = "oldSha256") @Required val oldSha256: kotlin.String,

    /* Sha256 of the on-disk binary after the refresh. */
    @SerialName(value = "sha256") @Required val sha256: kotlin.String,

    /* Size of the on-disk binary after the refresh. */
    @SerialName(value = "sizeBytes") @Required val sizeBytes: kotlin.Long,

    /* Source URL persisted on the row. Empty for buildbot-default cores. */
    @SerialName(value = "sourceUrl") @Required val sourceUrl: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

