/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param failed 
 * @param refreshed 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class RefreshCatalogOutputBody (

    @SerialName(value = "failed") @Required val failed: kotlin.Long,

    @SerialName(value = "refreshed") @Required val refreshed: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

