/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param gameCount 
 * @param name 
 * @param sharedDevelopers 
 */
@Serializable

data class RelatedPublisher (

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "sharedDevelopers") @Required val sharedDevelopers: kotlin.collections.List<kotlin.String>

) {


}

