/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GameResponse
import com.spela.client.models.ReplaceROMResult

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param game 
 * @param replacementResult 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ReplaceROMResponse (

    @SerialName(value = "game") @Required val game: GameResponse,

    @SerialName(value = "replacementResult") @Required val replacementResult: ReplaceROMResult,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

