/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param crc32 
 * @param previousCrc32 
 * @param previousStatus 
 * @param verified 
 * @param canonicalName 
 */
@Serializable

data class ReplaceROMResult (

    @SerialName(value = "crc32") @Required val crc32: kotlin.String,

    @SerialName(value = "previousCrc32") @Required val previousCrc32: kotlin.String,

    @SerialName(value = "previousStatus") @Required val previousStatus: kotlin.String,

    @SerialName(value = "verified") @Required val verified: kotlin.Boolean,

    @SerialName(value = "canonicalName") val canonicalName: kotlin.String? = null

) {


}

