/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param core 
 * @param error 
 * @param gameId 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ReportEmulatorErrorRequest (

    @SerialName(value = "core") @Required val core: kotlin.String,

    @SerialName(value = "error") @Required val error: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

