/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param current 
 * @param message 
 * @param phase 
 * @param total 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class ScanStatusResponse (

    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    @SerialName(value = "current") @Required val current: kotlin.Long,

    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "phase") @Required val phase: kotlin.String,

    @SerialName(value = "total") @Required val total: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

