/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param active 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param current 
 * @param message 
 * @param phase 
 * @param total 
 */
@Serializable

data class ScanStatusResponse (

    @SerialName(value = "active") @Required val active: kotlin.Boolean,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "current") val current: kotlin.Long? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "phase") val phase: kotlin.String? = null,

    @SerialName(value = "total") val total: kotlin.Long? = null

) {


}

