/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param error 
 * @param errorEligible 
 * @param matched 
 * @param notAttempted 
 * @param notFound 
 * @param notFoundEligible 
 * @param source 
 */
@Serializable

data class ScraperSourceResultResponse (

    @SerialName(value = "error") @Required val error: kotlin.Long,

    @SerialName(value = "errorEligible") @Required val errorEligible: kotlin.Long,

    @SerialName(value = "matched") @Required val matched: kotlin.Long,

    @SerialName(value = "notAttempted") @Required val notAttempted: kotlin.Long,

    @SerialName(value = "notFound") @Required val notFound: kotlin.Long,

    @SerialName(value = "notFoundEligible") @Required val notFoundEligible: kotlin.Long,

    @SerialName(value = "source") @Required val source: kotlin.String

) {


}

