/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param total 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param added 
 * @param jobId 
 * @param message 
 * @param totalItems 
 */
@Serializable

data class ScrapeStartedResponse (

    @SerialName(value = "total") @Required val total: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "added") val added: kotlin.Long? = null,

    @SerialName(value = "jobId") val jobId: kotlin.Long? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "totalItems") val totalItems: kotlin.Long? = null

) {


}

