/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleAbbreviation 
 * @param consoleColor 
 * @param consoleName 
 * @param gameId 
 * @param gameTitle 
 * @param url 
 */
@Serializable

data class ScreenshotItem (

    @SerialName(value = "consoleAbbreviation") @Required val consoleAbbreviation: kotlin.String,

    @SerialName(value = "consoleColor") @Required val consoleColor: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String

) {


}

