/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.SearchGameResult

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param results 
 * @param total 
 */
@Serializable

data class SearchCategoryResultSearchGameResult (

    @SerialName(value = "results") @Required val results: kotlin.collections.List<SearchGameResult>,

    @SerialName(value = "total") @Required val total: kotlin.Long

) {


}

