/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.GamePlatformResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param consoleId
 * @param consoleName
 * @param coverAspectRatio
 * @param coverUrl
 * @param developer
 * @param genre
 * @param id
 * @param platforms
 * @param title
 */
@Serializable

data class SearchGameResult (

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverAspectRatio") @Required val coverAspectRatio: kotlin.Double,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "developer") @Required val developer: kotlin.String,

    @SerialName(value = "genre") @Required val genre: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "platforms") @Required val platforms: kotlin.collections.List<GamePlatformResponse>,

    @SerialName(value = "title") @Required val title: kotlin.String

) {


}
