/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param colorTheme 
 * @param gameCount 
 * @param iconUrl 
 * @param id 
 * @param name 
 */
@Serializable

data class SearchConsoleResult (

    @SerialName(value = "colorTheme") @Required val colorTheme: kotlin.String,

    @SerialName(value = "gameCount") @Required val gameCount: kotlin.Long,

    @SerialName(value = "iconUrl") @Required val iconUrl: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

