/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.SeriesConsoleInfo
import com.spela.client.models.SeriesGameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoles 
 * @param games 
 * @param id 
 * @param igdbCollectionId 
 * @param libraryGames 
 * @param name 
 * @param totalGames 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param heroUrl 
 * @param logoUrl 
 */
@Serializable

data class SeriesDetailResponse (

    @SerialName(value = "consoles") @Required val consoles: kotlin.collections.List<SeriesConsoleInfo>?,

    @SerialName(value = "games") @Required val games: kotlin.collections.List<SeriesGameResponse>?,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "igdbCollectionId") @Required val igdbCollectionId: kotlin.Long,

    @SerialName(value = "libraryGames") @Required val libraryGames: kotlin.Long,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "totalGames") @Required val totalGames: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "heroUrl") val heroUrl: kotlin.String? = null,

    @SerialName(value = "logoUrl") val logoUrl: kotlin.String? = null

) {


}

