/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.DiagnosticCheck

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param checks Ordered list of server health checks.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class SetupDiagnosticsResponse (

    /* Ordered list of server health checks. */
    @SerialName(value = "checks") @Required val checks: kotlin.collections.List<DiagnosticCheck>,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

