/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param avatarUrl 
 * @param createdAt 
 * @param description 
 * @param downloadCount 
 * @param fileSize 
 * @param gameId 
 * @param id 
 * @param name 
 * @param screenshotUrl 
 * @param userId 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class SharedSaveResponse (

    @SerialName(value = "avatarUrl") @Required val avatarUrl: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "downloadCount") @Required val downloadCount: kotlin.Long,

    @SerialName(value = "fileSize") @Required val fileSize: kotlin.Long,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "screenshotUrl") @Required val screenshotUrl: kotlin.String,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

