/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param activeUserId 
 * @param createdAt 
 * @param gameId 
 * @param gameTitle 
 * @param id 
 * @param memberCount 
 * @param name 
 * @param ownerId 
 * @param ownerUsername 
 * @param status 
 * @param turnTakenAt 
 * @param updatedAt 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param activeUsername 
 * @param consoleName 
 * @param coreName 
 * @param gameCoverUrl 
 * @param sessionId 
 */
@Serializable

data class SharedSessionResponse (

    @SerialName(value = "activeUserId") @Required val activeUserId: kotlin.String?,

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "memberCount") @Required val memberCount: kotlin.Long,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "ownerId") @Required val ownerId: kotlin.String,

    @SerialName(value = "ownerUsername") @Required val ownerUsername: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "turnTakenAt") @Required val turnTakenAt: kotlinx.datetime.Instant?,

    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "activeUsername") val activeUsername: kotlin.String? = null,

    @SerialName(value = "consoleName") val consoleName: kotlin.String? = null,

    @SerialName(value = "coreName") val coreName: kotlin.String? = null,

    @SerialName(value = "gameCoverUrl") val gameCoverUrl: kotlin.String? = null,

    @SerialName(value = "sessionId") val sessionId: kotlin.String? = null

) {


}

