/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param sharedSessionId 
 * @param turnTakenAt 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class SharedSessionHeartbeatResponse (

    @SerialName(value = "sharedSessionId") @Required val sharedSessionId: kotlin.String,

    @SerialName(value = "turnTakenAt") @Required val turnTakenAt: kotlinx.datetime.Instant,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

