/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param gameTitle 
 * @param id 
 * @param inviteeId 
 * @param inviteeUsername 
 * @param inviterId 
 * @param inviterUsername 
 * @param sharedSessionId 
 * @param sharedSessionName 
 * @param status 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class SharedSessionInviteResponse (

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "inviteeId") @Required val inviteeId: kotlin.String,

    @SerialName(value = "inviteeUsername") @Required val inviteeUsername: kotlin.String,

    @SerialName(value = "inviterId") @Required val inviterId: kotlin.String,

    @SerialName(value = "inviterUsername") @Required val inviterUsername: kotlin.String,

    @SerialName(value = "sharedSessionId") @Required val sharedSessionId: kotlin.String,

    @SerialName(value = "sharedSessionName") @Required val sharedSessionName: kotlin.String,

    @SerialName(value = "status") @Required val status: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

