/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param downloadCount 
 * @param fileSize 
 * @param gameId 
 * @param id 
 * @param name 
 * @param userId 
 * @param username 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param avatarUrl 
 * @param description 
 * @param screenshotUrl 
 */
@Serializable

data class SharedSaveResponse (

    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "downloadCount") @Required val downloadCount: kotlin.Long,

    @SerialName(value = "fileSize") @Required val fileSize: kotlin.Long,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "userId") @Required val userId: kotlin.String,

    @SerialName(value = "username") @Required val username: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "avatarUrl") val avatarUrl: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "screenshotUrl") val screenshotUrl: kotlin.String? = null

) {


}

