/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param achievementRaId 
 * @param badgeUrl 
 * @param description 
 * @param gameTitle 
 * @param points 
 * @param raGameId 
 * @param rarityPercent 
 * @param showcaseOrder 
 * @param title 
 */
@Serializable

data class ShowcaseEntryResponse (

    @SerialName(value = "achievementRaId") @Required val achievementRaId: kotlin.Long,

    @SerialName(value = "badgeUrl") @Required val badgeUrl: kotlin.String,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "gameTitle") @Required val gameTitle: kotlin.String,

    @SerialName(value = "points") @Required val points: kotlin.Long,

    @SerialName(value = "raGameId") @Required val raGameId: kotlin.Long,

    @SerialName(value = "rarityPercent") @Required val rarityPercent: kotlin.Double,

    @SerialName(value = "showcaseOrder") @Required val showcaseOrder: kotlin.Long,

    @SerialName(value = "title") @Required val title: kotlin.String

) {


}

