/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.SessionStorageConsoleBreakdown

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param byConsole 
 * @param quotaBytes 
 * @param usedBytes 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class StorageUsageResponse (

    @SerialName(value = "byConsole") @Required val byConsole: kotlin.collections.List<SessionStorageConsoleBreakdown>,

    @SerialName(value = "quotaBytes") @Required val quotaBytes: kotlin.Long,

    @SerialName(value = "usedBytes") @Required val usedBytes: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

