/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param categoryCode 
 * @param categoryName 
 * @param createdAt 
 * @param eventType 
 * @param id 
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param dismissedAt 
 * @param ip 
 * @param metadata 
 * @param metadataRaw 
 * @param path 
 * @param reason 
 * @param userId 
 * @param username 
 */
@Serializable

data class SystemEventResponse (

    @SerialName(value = "categoryCode") @Required val categoryCode: kotlin.String,

    @SerialName(value = "categoryName") @Required val categoryName: kotlin.String,

    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    @SerialName(value = "eventType") @Required val eventType: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "dismissedAt") val dismissedAt: kotlin.time.Instant? = null,

    @SerialName(value = "ip") val ip: kotlin.String? = null,

    @SerialName(value = "metadata") val metadata: kotlinx.serialization.json.JsonObject? = null,

    @SerialName(value = "metadataRaw") val metadataRaw: kotlin.String? = null,

    @SerialName(value = "path") val path: kotlin.String? = null,

    @SerialName(value = "reason") val reason: kotlin.String? = null,

    @SerialName(value = "userId") val userId: kotlin.Long? = null,

    @SerialName(value = "username") val username: kotlin.String? = null

) {


}

