/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.TasteProfileConsole
import com.spela.client.models.TasteProfileGenre
import com.spela.client.models.TasteProfileTheme

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param genres 
 * @param themes 
 * @param topConsoles 
 * @param totalPlayTime 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class TasteProfileResponse (

    @SerialName(value = "genres") @Required val genres: kotlin.collections.List<TasteProfileGenre>,

    @SerialName(value = "themes") @Required val themes: kotlin.collections.List<TasteProfileTheme>,

    @SerialName(value = "topConsoles") @Required val topConsoles: kotlin.collections.List<TasteProfileConsole>,

    @SerialName(value = "totalPlayTime") @Required val totalPlayTime: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

