/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status Always 'reset' when the reset succeeded.
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class TestResetResponse (

    /* Always 'reset' when the reset succeeded. */
    @SerialName(value = "status") @Required val status: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

