/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param preferredGameId 
 * @param titleKey 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class TitlePlatformPreferenceResponse (

    @SerialName(value = "preferredGameId") @Required val preferredGameId: kotlin.String,

    @SerialName(value = "titleKey") @Required val titleKey: kotlin.String,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

