/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consoleId 
 * @param consoleName 
 * @param coverUrl 
 * @param gameId 
 * @param igdbCriticsRating 
 * @param name 
 * @param rank 
 */
@Serializable

data class TopListGameResponse (

    @SerialName(value = "consoleId") @Required val consoleId: kotlin.String,

    @SerialName(value = "consoleName") @Required val consoleName: kotlin.String,

    @SerialName(value = "coverUrl") @Required val coverUrl: kotlin.String,

    @SerialName(value = "gameId") @Required val gameId: kotlin.String,

    @SerialName(value = "igdbCriticsRating") @Required val igdbCriticsRating: kotlin.Double,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "rank") @Required val rank: kotlin.Long

) {


}

