/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param cheatsEnabled 
 * @param enabledIndices 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class UpdateSessionCheatsRequest (

    @SerialName(value = "cheatsEnabled") @Required val cheatsEnabled: kotlin.Boolean,

    @SerialName(value = "enabledIndices") @Required val enabledIndices: kotlin.collections.List<kotlin.Long>?,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

