/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.ConsoleKeyMappingDTO

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param autoLoadSaveEnabled 
 * @param autoSaveEnabled 
 * @param consoleKeyMappings 
 * @param consoleShaders 
 * @param customKeyMapping 
 * @param defaultSecondScreenPage 
 * @param preferredRegions 
 * @param selectedKeyMapping 
 * @param selectedShader 
 * @param selectedTheme 
 * @param showPerformanceOverlay 
 */
@Serializable

data class UpdatePreferencesRequest (

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "autoLoadSaveEnabled") val autoLoadSaveEnabled: kotlin.Boolean? = null,

    @SerialName(value = "autoSaveEnabled") val autoSaveEnabled: kotlin.Boolean? = null,

    @SerialName(value = "consoleKeyMappings") val consoleKeyMappings: kotlin.collections.Map<kotlin.String, ConsoleKeyMappingDTO>? = null,

    @SerialName(value = "consoleShaders") val consoleShaders: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "customKeyMapping") val customKeyMapping: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "defaultSecondScreenPage") val defaultSecondScreenPage: kotlin.String? = null,

    @SerialName(value = "preferredRegions") val preferredRegions: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "selectedKeyMapping") val selectedKeyMapping: kotlin.String? = null,

    @SerialName(value = "selectedShader") val selectedShader: kotlin.String? = null,

    @SerialName(value = "selectedTheme") val selectedTheme: kotlin.String? = null,

    @SerialName(value = "showPerformanceOverlay") val showPerformanceOverlay: kotlin.Boolean? = null

) {


}

