/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param lastPlayed 
 * @param playTime 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class UpdateGamePlayTimeResponse (

    @SerialName(value = "lastPlayed") @Required val lastPlayed: kotlinx.datetime.Instant,

    @SerialName(value = "playTime") @Required val playTime: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

