/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param consumePolicy Data classes we accept from this peer (class -> allowed).
 * @param sharePolicy Data classes we expose to this peer (class -> allowed).
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class UpdatePeerPolicyBody (

    /* Data classes we accept from this peer (class -> allowed). */
    @SerialName(value = "consumePolicy") @Required val consumePolicy: kotlin.collections.Map<kotlin.String, kotlin.Boolean>,

    /* Data classes we expose to this peer (class -> allowed). */
    @SerialName(value = "sharePolicy") @Required val sharePolicy: kotlin.collections.Map<kotlin.String, kotlin.Boolean>,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

