/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param clientReportId 
 * @param playedAt 
 * @param seconds 
 * @param updatePresence 
 */
@Serializable

data class UpdateGamePlayTimeRequest (

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "clientReportId") val clientReportId: kotlin.String? = null,

    @SerialName(value = "playedAt") val playedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "seconds") val seconds: kotlin.Long? = null,

    @SerialName(value = "updatePresence") val updatePresence: kotlin.Boolean? = null

) {


}

