/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.models

import com.spela.client.models.GameResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param currentStreak 
 * @param gamesPlayed 
 * @param lastPlayedAt 
 * @param longestStreak 
 * @param mostPlayedGame 
 * @param mostPlayedGameTime 
 * @param totalPlayTime 
 * @param dollarSchema A URL to the JSON Schema for this object.
 */
@Serializable

data class UserStatsResponse (

    @SerialName(value = "currentStreak") @Required val currentStreak: kotlin.Long,

    @SerialName(value = "gamesPlayed") @Required val gamesPlayed: kotlin.Long,

    @SerialName(value = "lastPlayedAt") @Required val lastPlayedAt: kotlin.time.Instant?,

    @SerialName(value = "longestStreak") @Required val longestStreak: kotlin.Long,

    @SerialName(value = "mostPlayedGame") @Required val mostPlayedGame: GameResponse,

    @SerialName(value = "mostPlayedGameTime") @Required val mostPlayedGameTime: kotlin.Long,

    @SerialName(value = "totalPlayTime") @Required val totalPlayTime: kotlin.Long,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null

) {


}

