/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.ConsoleKeyMappingDTO

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 *
 *
 * @param autoLoadSaveEnabled
 * @param autoSaveEnabled
 * @param autoUpdateCoresEnabled
 * @param consoleKeyMappings
 * @param consoleSaveStatePolicies
 * @param consoleShaders
 * @param customKeyMapping
 * @param defaultSecondScreenPage
 * @param gameSaveStatePolicies
 * @param preferredRegions
 * @param raHardcoreEnabled
 * @param raLinked
 * @param raUsername
 * @param selectedKeyMapping
 * @param selectedShader
 * @param selectedTheme
 * @param showPerformanceOverlay
 * @param dollarSchema A URL to the JSON Schema for this object.
 * @param consoleRenderScales
 */
@Serializable

data class UserPreferencesResponse (

    @SerialName(value = "autoLoadSaveEnabled") @Required val autoLoadSaveEnabled: kotlin.Boolean,

    @SerialName(value = "autoSaveEnabled") @Required val autoSaveEnabled: kotlin.Boolean,

    @SerialName(value = "autoUpdateCoresEnabled") @Required val autoUpdateCoresEnabled: kotlin.Boolean,

    @SerialName(value = "consoleKeyMappings") @Required val consoleKeyMappings: kotlin.collections.Map<kotlin.String, ConsoleKeyMappingDTO>,

    @SerialName(value = "consoleSaveStatePolicies") @Required val consoleSaveStatePolicies: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "consoleShaders") @Required val consoleShaders: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "customKeyMapping") @Required val customKeyMapping: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "defaultSecondScreenPage") @Required val defaultSecondScreenPage: kotlin.String,

    @SerialName(value = "gameSaveStatePolicies") @Required val gameSaveStatePolicies: kotlin.collections.Map<kotlin.String, kotlin.String>,

    @SerialName(value = "preferredRegions") @Required val preferredRegions: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "raHardcoreEnabled") @Required val raHardcoreEnabled: kotlin.Boolean,

    @SerialName(value = "raLinked") @Required val raLinked: kotlin.Boolean,

    @SerialName(value = "raUsername") @Required val raUsername: kotlin.String,

    @SerialName(value = "selectedKeyMapping") @Required val selectedKeyMapping: kotlin.String,

    @SerialName(value = "selectedShader") @Required val selectedShader: kotlin.String,

    @SerialName(value = "selectedTheme") @Required val selectedTheme: kotlin.String,

    @SerialName(value = "showPerformanceOverlay") @Required val showPerformanceOverlay: kotlin.Boolean,

    /* A URL to the JSON Schema for this object. */
    @SerialName(value = "\$schema") val dollarSchema: kotlin.String? = null,

    @SerialName(value = "consoleRenderScales") val consoleRenderScales: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}
