/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.spela.client.models

import com.spela.client.models.WizardOption

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param options 
 * @param step 
 * @param title 
 * @param type 
 */
@Serializable

data class WizardStep (

    @SerialName(value = "options") @Required val options: kotlin.collections.List<WizardOption>?,

    @SerialName(value = "step") @Required val step: kotlin.Long,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

