#!/bin/sh
#
# Generates a .env file with random secrets for Spela QA/production deployment.
# Run once before first deploy. Safe to re-run — will not overwrite existing .env.
#
# Usage:
#   ./generate-secrets.sh
#   ./generate-secrets.sh --force   # overwrite existing .env
#

set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ] && [ "$1" != "--force" ]; then
    echo "Error: $ENV_FILE already exists. Use --force to overwrite."
    exit 1
fi

generate_secret() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

SPELA_JWT_SECRET=$(generate_secret 48)
TURN_SECRET=$(generate_secret 48)

cat > "$ENV_FILE" <<EOF
# Generated by generate-secrets.sh — do not commit this file.

# JWT signing key (required)
SPELA_JWT_SECRET=$SPELA_JWT_SECRET

# TURN server shared secret for HMAC-SHA1 credentials (required for netplay)
TURN_SECRET=$TURN_SECRET

# Public domain or IP of this server (used by TURN and player app)
TURN_HOST=

# Host path to your ROM directory
SPELA_GAMES_PATH=/data/spela/games

# ScreenScraper credentials (optional — enables game metadata/cover art)
# SPELA_SCRAPER_DEV_ID=
# SPELA_SCRAPER_DEV_PASS=
# SPELA_SCRAPER_USER=
# SPELA_SCRAPER_USER_PASS=

# Public IP if the server is behind NAT (coturn usually auto-detects)
# TURN_EXTERNAL_IP=
EOF

echo "Created $ENV_FILE with fresh secrets."
echo ""
echo "Next steps:"
echo "  1. Edit $ENV_FILE and set TURN_HOST to your domain (e.g. spela.example.com)"
echo "  2. Set SPELA_GAMES_PATH to where your ROMs are stored"
echo "  3. Deploy: docker compose -f docker-compose.qa.yml up -d --build"
