#!/bin/sh
#
# Spela — Interactive first-time setup
#
# Guides the server admin through creating the .env file, then optionally
# builds and starts the QA stack with docker compose.
#
# Usage:
#   git clone https://github.com/mattias800/spela.git && cd spela
#   ./setup.sh
#

set -e

# ── Helpers ─────────────────────────────────────────────────────────
generate_secret() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

prompt() {
    # prompt VARNAME "Question" "default"
    _var="$1"; _question="$2"; _default="$3"
    if [ -n "$_default" ]; then
        printf "%s [%s]: " "$_question" "$_default"
    else
        printf "%s: " "$_question"
    fi
    read -r _answer
    _answer="${_answer:-$_default}"
    eval "$_var=\"\$_answer\""
}

prompt_optional() {
    # prompt_optional VARNAME "Question"
    _var="$1"; _question="$2"
    printf "%s (leave blank to skip): " "$_question"
    read -r _answer
    eval "$_var=\"\$_answer\""
}

prompt_yes_no() {
    # prompt_yes_no "Question" — returns 0 for yes, 1 for no
    printf "%s [Y/n]: " "$1"
    read -r _yn
    case "$_yn" in
        [nN]*) return 1 ;;
        *) return 0 ;;
    esac
}

# ── Header ──────────────────────────────────────────────────────────
echo ""
echo "========================================="
echo "  Spela Server Setup"
echo "========================================="
echo ""

# ── Check for existing .env ─────────────────────────────────────────
if [ -f .env ]; then
    echo "An existing .env file was found."
    echo ""
    if ! prompt_yes_no "Overwrite it?"; then
        echo "Setup cancelled. Your existing .env was not modified."
        exit 0
    fi
    echo ""
fi

# ── Required: hostname ──────────────────────────────────────────────
echo "-- Server hostname --"
echo ""
echo "This is the public domain or IP that players will use to connect."
echo "Examples: spela.example.com, 192.168.1.100, my-server.local"
echo ""
prompt HOSTNAME "Hostname or IP"
while [ -z "$HOSTNAME" ]; do
    echo "  Hostname is required."
    prompt HOSTNAME "Hostname or IP"
done
echo ""

# ── Required: games path ────────────────────────────────────────────
echo "-- Games directory --"
echo ""
echo "Path on the host where your ROM files are stored."
echo "This directory will be mounted read-only into the container."
echo ""
prompt GAMES_PATH "Games directory path" "/data/spela/games"
echo ""

# ── Optional: BIOS path ─────────────────────────────────────────────
echo "-- BIOS directory (optional) --"
echo ""
echo "Some systems (PS1, Saturn, etc.) require BIOS files."
echo ""
prompt_optional BIOS_PATH "BIOS directory path"
echo ""

# ── Optional: ScreenScraper ──────────────────────────────────────────
echo "-- ScreenScraper (optional) --"
echo ""
echo "ScreenScraper provides game metadata and cover art."
echo "Create a free account at https://www.screenscraper.fr"
echo ""
SCRAPER_USER=""
SCRAPER_PASS=""
if prompt_yes_no "Configure ScreenScraper credentials?"; then
    prompt_optional SCRAPER_USER "ScreenScraper username"
    prompt_optional SCRAPER_PASS "ScreenScraper password"
fi
echo ""

# ── Generate secrets ─────────────────────────────────────────────────
echo "Generating secrets..."
JWT_SECRET=$(generate_secret 48)
TURN_SECRET_VAL=$(generate_secret 48)
echo "  Done."
echo ""

# ── Write .env ───────────────────────────────────────────────────────
cat > .env <<EOF
# Generated by setup.sh — do not commit this file.

# JWT signing key (required — auto-generated)
SPELA_JWT_SECRET=$JWT_SECRET

# TURN server shared secret for HMAC-SHA1 credentials (required for netplay)
TURN_SECRET=$TURN_SECRET_VAL

# Public domain or IP of this server
TURN_HOST=$HOSTNAME

# Host path to your ROM directory
SPELA_GAMES_PATH=$GAMES_PATH
EOF

if [ -n "$BIOS_PATH" ]; then
    cat >> .env <<EOF

# Host path to your BIOS directory
SPELA_BIOS_PATH=$BIOS_PATH
EOF
fi

if [ -n "$SCRAPER_USER" ]; then
    cat >> .env <<EOF

# ScreenScraper credentials
SPELA_SCRAPER_USER=$SCRAPER_USER
SPELA_SCRAPER_USER_PASS=$SCRAPER_PASS
EOF
fi

# ── Summary ──────────────────────────────────────────────────────────
echo "========================================="
echo "  Setup complete!"
echo "========================================="
echo ""
echo "  .env written with the following configuration:"
echo ""
echo "  Hostname:       $HOSTNAME"
echo "  Games path:     $GAMES_PATH"
[ -n "$BIOS_PATH" ] && echo "  BIOS path:      $BIOS_PATH"
[ -n "$SCRAPER_USER" ] && echo "  ScreenScraper:  $SCRAPER_USER"
echo "  JWT secret:     ${JWT_SECRET%"${JWT_SECRET#????????}"}... (auto-generated)"
echo "  TURN secret:    ${TURN_SECRET_VAL%"${TURN_SECRET_VAL#????????}"}... (auto-generated)"
echo ""

# ── Optionally start ─────────────────────────────────────────────────
if prompt_yes_no "Start the server now? (requires Docker)"; then
    echo ""
    echo "Building and starting Spela..."
    echo "  This will take a few minutes on the first run."
    echo ""
    docker compose -f docker-compose.qa.yml up --build -d
    echo ""
    echo "Spela is starting! Once ready, open:"
    echo "  http://$HOSTNAME:8080"
    echo ""
    echo "To view logs:     docker compose -f docker-compose.qa.yml logs -f"
    echo "To stop:          docker compose -f docker-compose.qa.yml down"
    echo "To update later:  ./update.sh"
else
    echo "To start the server manually:"
    echo "  docker compose -f docker-compose.qa.yml up --build -d"
    echo ""
    echo "To update later:  ./update.sh"
fi
