#!/bin/sh
#
# Spela — Interactive first-time setup
#
# Guides the server admin through creating the .env file.
# All prompts go to stderr so stdout only contains the .env content.
#
# Usage:
#   git clone https://github.com/mattias800/spela.git && cd spela
#   ./setup.sh          # prints .env content to stdout
#   ./setup.sh > .env   # write directly to .env
#

set -e

# ── Helpers (all output to stderr) ───────────────────────────────────
generate_secret() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

prompt() {
    # prompt VARNAME "Question" "default"
    _var="$1"; _question="$2"; _default="$3"
    if [ -n "$_default" ]; then
        printf "%s [%s]: " "$_question" "$_default" >&2
    else
        printf "%s: " "$_question" >&2
    fi
    read -r _answer
    _answer="${_answer:-$_default}"
    eval "$_var=\"\$_answer\""
}

prompt_optional() {
    # prompt_optional VARNAME "Question"
    _var="$1"; _question="$2"
    printf "%s (leave blank to skip): " "$_question" >&2
    read -r _answer
    eval "$_var=\"\$_answer\""
}

prompt_yes_no() {
    # prompt_yes_no "Question" — returns 0 for yes, 1 for no
    printf "%s [Y/n]: " "$1" >&2
    read -r _yn
    case "$_yn" in
        [nN]*) return 1 ;;
        *) return 0 ;;
    esac
}

info() {
    echo "$@" >&2
}

# ── Header ──────────────────────────────────────────────────────────
info ""
info "========================================="
info "  Spela Server Setup"
info "========================================="
info ""

# ── Required: hostname ──────────────────────────────────────────────
info "-- Server hostname --"
info ""
info "This is the public domain or IP that players will use to connect."
info "Examples: spela.example.com, 192.168.1.100, my-server.local"
info ""
prompt HOSTNAME "Hostname or IP"
while [ -z "$HOSTNAME" ]; do
    info "  Hostname is required."
    prompt HOSTNAME "Hostname or IP"
done
info ""

# ── Required: games path ────────────────────────────────────────────
info "-- Games directory --"
info ""
info "Path on the host where your ROM files are stored."
info "This directory will be mounted read-only into the container."
info ""
prompt GAMES_PATH "Games directory path" "/data/spela/games"
info ""

# ── Optional: BIOS path ─────────────────────────────────────────────
info "-- BIOS directory (optional) --"
info ""
info "Some systems (PS1, Saturn, etc.) require BIOS files."
info ""
prompt_optional BIOS_PATH "BIOS directory path"
info ""

# ── Optional: ScreenScraper ──────────────────────────────────────────
info "-- ScreenScraper (optional) --"
info ""
info "ScreenScraper provides game metadata and cover art."
info "Create a free account at https://www.screenscraper.fr"
info ""
SCRAPER_USER=""
SCRAPER_PASS=""
if prompt_yes_no "Configure ScreenScraper credentials?"; then
    prompt_optional SCRAPER_USER "ScreenScraper username"
    prompt_optional SCRAPER_PASS "ScreenScraper password"
fi
info ""

# ── Generate secrets ─────────────────────────────────────────────────
info "Generating secrets..."
JWT_SECRET=$(generate_secret 48)
ENCRYPTION_KEY=$(generate_secret 48)
TURN_SECRET_VAL=$(generate_secret 48)
info "  Done."
info ""

# ── Build .env content ───────────────────────────────────────────────
ENV_CONTENT="# Generated by setup.sh — do not commit this file.

# JWT signing key (required — auto-generated)
SPELA_JWT_SECRET=$JWT_SECRET

# Encryption key for stored credentials (required — auto-generated)
SPELA_ENCRYPTION_KEY=$ENCRYPTION_KEY

# TURN server shared secret for HMAC-SHA1 credentials (required for netplay)
TURN_SECRET=$TURN_SECRET_VAL

# Public domain or IP of this server
TURN_HOST=$HOSTNAME

# Host path to your ROM directory
SPELA_GAMES_PATH=$GAMES_PATH"

if [ -n "$BIOS_PATH" ]; then
    ENV_CONTENT="$ENV_CONTENT

# Host path to your BIOS directory
SPELA_BIOS_PATH=$BIOS_PATH"
fi

if [ -n "$SCRAPER_USER" ]; then
    ENV_CONTENT="$ENV_CONTENT

# ScreenScraper credentials
SPELA_SCRAPER_USER=$SCRAPER_USER
SPELA_SCRAPER_USER_PASS=$SCRAPER_PASS"
fi

# ── Print result ─────────────────────────────────────────────────────
info "========================================="
info "  Setup complete!"
info "========================================="
info ""
info "  Copy the output below into your .env file,"
info "  or re-run with:  ./setup.sh > .env"
info ""
info "─────────────── .env ───────────────────"

echo "$ENV_CONTENT"

info "─────────────────────────────────────────"
