/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.spela.client.apis

import com.spela.client.models.AchievementLeaderboardResponse
import com.spela.client.models.AchievementTimelineResponse
import com.spela.client.models.AdminRAStatusResponse
import com.spela.client.models.HumaError
import com.spela.client.models.LinkRAAccountRequest
import com.spela.client.models.RALinkResponse
import com.spela.client.models.RAStatusResponse
import com.spela.client.models.RATokenResponse
import com.spela.client.models.RAUnlinkResponse
import com.spela.client.models.RecentAchievementsResponse
import com.spela.client.models.RefreshAchievementsResponse
import com.spela.client.models.ShowcaseEntryInput
import com.spela.client.models.ShowcaseEntryResponse
import com.spela.client.models.UnlockedAchievementsResponse
import com.spela.client.models.UpdateRASettingsRequest

import com.spela.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class RetroachievementsApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Get achievement leaderboard
     * Returns per-user achievement counts and points for a specific game, sorted by unlocked count.
     * @param id Game ID.
     * @return AchievementLeaderboardResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAchievementLeaderboard(id: kotlin.String): HttpResponse<AchievementLeaderboardResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/games/{id}/achievements/leaderboard".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get achievement progress
     * Returns the caller&#39;s achievement progress for a specific game, enriched with playTimeAtUnlock. Returns an empty array if no RA account is linked.
     * @param id Game ID.
     * @return kotlin.Any
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAchievementProgress(id: kotlin.String): HttpResponse<kotlin.Any> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/games/{id}/achievements/progress".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get achievement showcase
     * Returns the caller&#39;s showcased achievements in display order.
     * @return kotlin.collections.List<ShowcaseEntryResponse>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAchievementShowcase(): HttpResponse<kotlin.collections.List<ShowcaseEntryResponse>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/user/achievements/showcase",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetAchievementShowcaseResponse>().map { value }
    }

    @Serializable(GetAchievementShowcaseResponse.Companion::class)
    private class GetAchievementShowcaseResponse(val value: List<ShowcaseEntryResponse>) {
        companion object : KSerializer<GetAchievementShowcaseResponse> {
            private val serializer: KSerializer<List<ShowcaseEntryResponse>> = serializer<List<ShowcaseEntryResponse>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetAchievementShowcaseResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetAchievementShowcaseResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get achievement timeline
     * Returns the caller&#39;s achievement timeline for a specific game, ordered chronologically.
     * @param id Game ID.
     * @return AchievementTimelineResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAchievementTimeline(id: kotlin.String): HttpResponse<AchievementTimelineResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/games/{id}/achievements/timeline".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get RetroAchievements API status
     * Admin-only. Returns whether the server-level RA API key is configured and the credential source (env, database, none).
     * @return AdminRAStatusResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAdminRAStatus(): HttpResponse<AdminRAStatusResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/admin/ra/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get a user&#39;s achievement showcase
     * Returns another user&#39;s showcased achievements.
     * @param id User ID.
     * @return kotlin.collections.List<ShowcaseEntryResponse>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getPublicAchievementShowcase(id: kotlin.String): HttpResponse<kotlin.collections.List<ShowcaseEntryResponse>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/users/{id}/achievements/showcase".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetPublicAchievementShowcaseResponse>().map { value }
    }

    @Serializable(GetPublicAchievementShowcaseResponse.Companion::class)
    private class GetPublicAchievementShowcaseResponse(val value: List<ShowcaseEntryResponse>) {
        companion object : KSerializer<GetPublicAchievementShowcaseResponse> {
            private val serializer: KSerializer<List<ShowcaseEntryResponse>> = serializer<List<ShowcaseEntryResponse>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetPublicAchievementShowcaseResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetPublicAchievementShowcaseResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get RA account link status
     * Returns whether the caller has linked a RA account, the linked username, and the hardcore flag.
     * @return RAStatusResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getRAAccountStatus(): HttpResponse<RAStatusResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/user/ra/status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get RA credentials for the native player
     * Returns the caller&#39;s RA username and decrypted token. Response is marked no-store.
     * @return RATokenResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getRAToken(): HttpResponse<RATokenResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/user/ra/token",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get recent achievements
     * Returns the caller&#39;s 20 most recently unlocked achievements across all games.
     * @return RecentAchievementsResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getRecentAchievements(): HttpResponse<RecentAchievementsResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/user/achievements/recent",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get all unlocked achievements
     * Returns every unlocked achievement across all games, enriched with title, badge and rarity. Used by the showcase picker.
     * @return UnlockedAchievementsResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getUnlockedAchievements(): HttpResponse<UnlockedAchievementsResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/user/achievements/unlocked",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Link a RetroAchievements account
     * Exchanges username + password for a RetroAchievements token and stores it encrypted for the caller.
     * @param linkRAAccountRequest 
     * @return RALinkResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun linkRAAccount(linkRAAccountRequest: LinkRAAccountRequest): HttpResponse<RALinkResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = linkRAAccountRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/user/ra/link",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Refresh achievement cache
     * Admin-only. Deletes the achievement cache entries for a game so the next request re-fetches from RetroAchievements.
     * @param id Game ID.
     * @return RefreshAchievementsResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun refreshAchievements(id: kotlin.String): HttpResponse<RefreshAchievementsResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/admin/games/{id}/achievements/refresh".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Unlink the RetroAchievements account
     * Removes the caller&#39;s stored RA credentials.
     * @return RAUnlinkResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun unlinkRAAccount(): HttpResponse<RAUnlinkResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/user/ra/link",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Replace the achievement showcase
     * Replaces the caller&#39;s showcased achievements. Maximum 5 entries.
     * @param showcaseEntryInput 
     * @return kotlin.collections.List<ShowcaseEntryResponse>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateAchievementShowcase(showcaseEntryInput: kotlin.collections.List<ShowcaseEntryInput>): HttpResponse<kotlin.collections.List<ShowcaseEntryResponse>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = UpdateAchievementShowcaseRequest(showcaseEntryInput)

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/user/achievements/showcase",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<UpdateAchievementShowcaseResponse>().map { value }
    }

    @Serializable(UpdateAchievementShowcaseRequest.Companion::class)
    private class UpdateAchievementShowcaseRequest(val value: List<ShowcaseEntryInput>) {
        companion object : KSerializer<UpdateAchievementShowcaseRequest> {
            private val serializer: KSerializer<List<ShowcaseEntryInput>> = serializer<List<ShowcaseEntryInput>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: UpdateAchievementShowcaseRequest) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = UpdateAchievementShowcaseRequest(serializer.deserialize(decoder))
        }
    }
    @Serializable(UpdateAchievementShowcaseResponse.Companion::class)
    private class UpdateAchievementShowcaseResponse(val value: List<ShowcaseEntryResponse>) {
        companion object : KSerializer<UpdateAchievementShowcaseResponse> {
            private val serializer: KSerializer<List<ShowcaseEntryResponse>> = serializer<List<ShowcaseEntryResponse>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: UpdateAchievementShowcaseResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = UpdateAchievementShowcaseResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Update RA settings
     * Updates RA-specific settings for the caller (currently only the hardcore flag).
     * @param updateRASettingsRequest 
     * @return RAStatusResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateRASettings(updateRASettingsRequest: UpdateRASettingsRequest): HttpResponse<RAStatusResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = updateRASettingsRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/user/ra/settings",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
