package db

import "strings"

// ConsoleSpec is the single source of truth for one console's static
// metadata (#1443). The seeders build every console row from this
// registry, and response builders derive presentation fields from it,
// so this catalog — not the database — is authoritative for everything
// here. SaveStatePolicy carries only the seed default: the DB column
// stays authoritative once an admin overrides it.
type ConsoleSpec struct {
	Abbreviation string
	Name         string
	Code         string // canonical short code; "" when none assigned
	Extensions   string // comma-separated file extensions

	DefaultCore    string
	EmulatorJSCore string
	FolderName     string

	CoverAspect string // "" = use the schema default (3:4)
	ColorTheme  string
	Tag         *string // optional short card qualifier (e.g. "Demos")

	Generation int
	MakerCode  string // hardware maker code; "" when none
	MediaCode  string // media type code; "" when none

	ReleaseYear *int
	UnitsSold   *int64
	Summary     *string

	Playable         bool
	SaveStateSupport bool
	SaveStatePolicy  SaveStatePolicy
}

// consoleRegistry is the ordered console catalog and the single source of
// truth for static console metadata. Edit entries directly; the
// TestConsoleSeedGolden snapshot guards the seeded catalog against
// accidental drift.
var consoleRegistry = []ConsoleSpec{
	{Abbreviation: "NES", Name: "Nintendo Entertainment System", Code: "nes", Extensions: ".nes,.fds", DefaultCore: "nestopia", EmulatorJSCore: "nestopia", FolderName: "nes", CoverAspect: "5:7", ColorTheme: "#e60012", Generation: 3, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1983), UnitsSold: int64Ptr(61910000), Summary: strPtr("The Nintendo Entertainment System revived the video game industry after the 1983 crash and established Nintendo as a dominant force in gaming. With iconic franchises like Super Mario Bros., The Legend of Zelda, and Metroid, it defined the template for home console gaming for decades to come."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "FDS", Name: "Famicom Disk System", Code: "fds", Extensions: ".fds", DefaultCore: "nestopia", EmulatorJSCore: "nestopia", FolderName: "fds", CoverAspect: "1:1", ColorTheme: "#e60012", Generation: 3, MakerCode: "nintendo", MediaCode: "floppy-disk", ReleaseYear: intPtr(1986), UnitsSold: int64Ptr(4440000), Summary: strPtr("The Famicom Disk System was a Japan-exclusive add-on for the Famicom that used rewritable floppy disks, enabling larger games, saved data, and lower-cost distribution through disk-rewriting kiosks. It debuted landmark titles including the original versions of The Legend of Zelda, Metroid, and Kid Icarus."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SMS", Name: "Sega Master System", Code: "sms", Extensions: ".sms", DefaultCore: "genesis_plus_gx", EmulatorJSCore: "segaMS", FolderName: "mastersystem", ColorTheme: "#0060a8", Generation: 3, MakerCode: "sega", MediaCode: "cartridge", ReleaseYear: intPtr(1985), UnitsSold: int64Ptr(13000000), Summary: strPtr("The Sega Master System was Sega's first major home console and a strong competitor to the NES in Europe and Brazil. While it was technically superior to the NES, Nintendo's exclusive licensing agreements limited its game library and market share in North America and Japan."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SG1K", Name: "Sega SG-1000", Code: "sg1000", Extensions: ".sg,.sc,.sf7,.bin", DefaultCore: "genesis_plus_gx", EmulatorJSCore: "segaMS", FolderName: "sg-1000", ColorTheme: "#0060a8", Generation: 3, MakerCode: "sega", MediaCode: "cartridge", ReleaseYear: intPtr(1983), Summary: strPtr("The Sega SG-1000 was Sega's first home console, launched in Japan on the same day as the Nintendo Famicom. While it was commercially overshadowed by Nintendo, it established Sega in the console market and its hardware architecture evolved directly into the more successful Sega Master System."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "A78", Name: "Atari 7800", Code: "a78", Extensions: ".a78,.bin", DefaultCore: "prosystem", EmulatorJSCore: "prosystem", FolderName: "atari7800", ColorTheme: "#1c1c1c", Generation: 3, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1986), UnitsSold: int64Ptr(3770000), Summary: strPtr("The Atari 7800 was designed to be backward compatible with the Atari 2600 and featured improved graphics rivaling the NES. Delayed by two years due to Atari's sale to Jack Tramiel, it arrived too late to challenge Nintendo's dominance despite its competitive hardware."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SNES", Name: "Super Nintendo", Code: "snes", Extensions: ".sfc,.smc", DefaultCore: "snes9x", EmulatorJSCore: "snes9x", FolderName: "snes", CoverAspect: "4:3", ColorTheme: "#7b7db5", Generation: 4, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1990), UnitsSold: int64Ptr(49100000), Summary: strPtr("The Super Nintendo Entertainment System delivered a generational leap with Mode 7 graphics, advanced sound capabilities, and an extraordinary game library. Titles like Super Mario World, A Link to the Past, and Chrono Trigger are widely regarded as some of the greatest games ever made."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "GEN", Name: "Sega Genesis", Code: "genesis", Extensions: ".md,.gen,.bin", DefaultCore: "genesis_plus_gx", EmulatorJSCore: "segaMD", FolderName: "genesis", ColorTheme: "#1565c0", Generation: 4, MakerCode: "sega", MediaCode: "cartridge", ReleaseYear: intPtr(1988), UnitsSold: int64Ptr(30750000), Summary: strPtr("The Sega Genesis, known as the Mega Drive outside North America, was Sega's most successful console and a fierce rival to the SNES. Its aggressive marketing campaign and Sonic the Hedgehog made it the first serious challenger to Nintendo's dominance in the home console market."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "GB", Name: "Game Boy", Code: "gb", Extensions: ".gb", DefaultCore: "gambatte", EmulatorJSCore: "gambatte", FolderName: "gb", CoverAspect: "7:8", ColorTheme: "#2e3a08", Generation: 4, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1989), UnitsSold: int64Ptr(118690000), Summary: strPtr("The Game Boy launched portable gaming into the mainstream with its compact design and exceptional battery life. Bundled with Tetris at launch, it dominated the handheld market for over a decade despite its monochrome green-tinted screen."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "GG", Name: "Game Gear", Code: "gamegear", Extensions: ".gg", DefaultCore: "genesis_plus_gx", EmulatorJSCore: "segaGG", FolderName: "gamegear", CoverAspect: "1:1", ColorTheme: "#1a1a1a", Generation: 4, MakerCode: "sega", MediaCode: "cartridge", ReleaseYear: intPtr(1990), UnitsSold: int64Ptr(10620000), Summary: strPtr("The Sega Game Gear was a portable console with a full-color backlit screen, positioned as a direct competitor to the Game Boy. Essentially a portable Master System, it offered superior graphics but suffered from short battery life and a higher price point."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PCE", Name: "TurboGrafx-16", Code: "pce", Extensions: ".pce", DefaultCore: "mednafen_pce", EmulatorJSCore: "mednafen_pce", FolderName: "tg16", ColorTheme: "#ff6600", Generation: 4, MakerCode: "nec", MediaCode: "hucard", ReleaseYear: intPtr(1987), UnitsSold: int64Ptr(10000000), Summary: strPtr("The TurboGrafx-16, developed jointly by NEC and Hudson Soft, was the first console of the 16-bit era. It used compact HuCard cartridges and was hugely popular in Japan, though it struggled against the Genesis and SNES in Western markets."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PCECD", Name: "TurboGrafx-CD", Code: "pcecd", Extensions: ".chd,.cue,.iso,.m3u", DefaultCore: "mednafen_pce", EmulatorJSCore: "mednafen_pce", FolderName: "tg16cd", ColorTheme: "#ff6600", Generation: 4, MakerCode: "nec", MediaCode: "cd-rom", ReleaseYear: intPtr(1988), Summary: strPtr("The TurboGrafx-CD was a CD-ROM add-on for the TurboGrafx-16, making it one of the first CD-based gaming platforms. It enabled larger games with CD-quality audio and full-motion video, pioneering the shift from cartridges to optical media in console gaming."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SGX", Name: "PC Engine SuperGrafx", Code: "sgx", Extensions: ".sgx,.pce", DefaultCore: "mednafen_supergrafx", FolderName: "supergrafx", ColorTheme: "#ff6600", Generation: 4, MakerCode: "nec", MediaCode: "hucard", ReleaseYear: intPtr(1989), Summary: strPtr("The PC Engine SuperGrafx was an enhanced version of the PC Engine with additional video hardware for improved sprite and background capabilities. Only seven games were released specifically for the system, making it one of the shortest-lived and rarest consoles, though it maintained full backward compatibility with the original PC Engine library."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "NEOGEO", Name: "Neo Geo", Code: "neogeo", Extensions: ".zip", DefaultCore: "fbneo", EmulatorJSCore: "fbneo", FolderName: "neogeo", ColorTheme: "#ffcc00", Generation: 4, MakerCode: "snk", MediaCode: "cartridge", ReleaseYear: intPtr(1990), UnitsSold: int64Ptr(1000000), Summary: strPtr("The Neo Geo AES brought arcade-perfect gaming to the home by using identical hardware to SNK's arcade cabinets. Its premium price tag and expensive cartridges made it a luxury item, but its fighting game library featuring The King of Fighters and Fatal Fury was unmatched."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "NEOCD", Name: "Neo Geo CD", Code: "neocd", Extensions: ".chd,.cue,.iso", DefaultCore: "neocd", FolderName: "neogeocd", ColorTheme: "#1c1c1c", Generation: 4, MakerCode: "snk", MediaCode: "cd-rom", ReleaseYear: intPtr(1994), Summary: strPtr("The Neo Geo CD was SNK's more affordable alternative to the expensive AES cartridge system, using CD-ROM media to drastically reduce game prices. However, its single-speed CD drive resulted in extremely long loading times that frustrated players despite access to the same excellent arcade library."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "LYNX", Name: "Atari Lynx", Code: "lynx", Extensions: ".lnx,.lyx", DefaultCore: "handy", EmulatorJSCore: "handy", FolderName: "atarilynx", CoverAspect: "1:1", ColorTheme: "#8b4513", Generation: 4, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1989), UnitsSold: int64Ptr(3000000), Summary: strPtr("The Atari Lynx was the first handheld console with a color LCD screen and hardware sprite scaling. Despite its technical superiority over the Game Boy, its large size, high price, and short battery life limited its commercial success."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SCD", Name: "Sega CD", Code: "segacd", Extensions: ".iso,.bin,.cue,.m3u", DefaultCore: "genesis_plus_gx", EmulatorJSCore: "segaCD", FolderName: "segacd", ColorTheme: "#0a8d7b", Generation: 4, MakerCode: "sega", MediaCode: "cd-rom", ReleaseYear: intPtr(1991), UnitsSold: int64Ptr(2240000), Summary: strPtr("The Sega CD was a CD-ROM add-on for the Genesis that enabled full-motion video, CD-quality audio, and larger game worlds. While it produced standout titles like Sonic CD and Lunar, many of its games relied heavily on grainy FMV gimmicks."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "CDI", Name: "Philips CD-i", Code: "cdi", Extensions: ".chd,.cue,.iso", DefaultCore: "same_cdi", EmulatorJSCore: "same_cdi", FolderName: "cdi", ColorTheme: "#006633", Generation: 4, MakerCode: "philips", MediaCode: "cd-rom", ReleaseYear: intPtr(1991), UnitsSold: int64Ptr(570000), Summary: strPtr("The Philips CD-i was an interactive multimedia player that also functioned as a game console. Despite its ambitious vision as an all-in-one entertainment device, it is best remembered for its poorly received Zelda and Mario games licensed from Nintendo."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PSX", Name: "PlayStation", Code: "psx", Extensions: ".bin,.cue,.iso,.pbp,.m3u", DefaultCore: "beetle_psx_hw", EmulatorJSCore: "mednafen_psx_hw", FolderName: "psx", CoverAspect: "1:1", ColorTheme: "#003087", Generation: 5, MakerCode: "sony", MediaCode: "cd-rom", ReleaseYear: intPtr(1994), UnitsSold: int64Ptr(102490000), Summary: strPtr("The PlayStation was Sony's debut in the console market and became one of the best-selling consoles of all time. Its CD-ROM format attracted third-party developers with lower manufacturing costs, spawning landmark franchises like Final Fantasy VII, Metal Gear Solid, and Crash Bandicoot."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "N64", Name: "Nintendo 64", Code: "n64", Extensions: ".n64,.z64,.v64", DefaultCore: "parallel_n64", EmulatorJSCore: "mupen64plus_next", FolderName: "n64", CoverAspect: "10:7", ColorTheme: "#06492e", Generation: 5, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1996), UnitsSold: int64Ptr(32930000), Summary: strPtr("The Nintendo 64 pioneered 3D console gaming with revolutionary titles like Super Mario 64, The Legend of Zelda: Ocarina of Time, and GoldenEye 007. Its decision to use cartridges over CD-ROMs limited third-party support but enabled faster load times and introduced the analog stick to mainstream gaming."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "SAT", Name: "Sega Saturn", Code: "saturn", Extensions: ".iso,.bin,.cue,.chd,.m3u", DefaultCore: "yabause", EmulatorJSCore: "yabause", FolderName: "saturn", ColorTheme: "#0a4da2", Generation: 5, MakerCode: "sega", MediaCode: "cd-rom", ReleaseYear: intPtr(1994), UnitsSold: int64Ptr(9260000), Summary: strPtr("The Sega Saturn featured powerful 2D capabilities and a dual-CPU architecture that was notoriously difficult to program for. While it thrived in Japan with titles like Nights into Dreams and Virtua Fighter 2, its surprise early launch in North America damaged retailer relationships and developer support."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "GBC", Name: "Game Boy Color", Code: "gbc", Extensions: ".gbc", DefaultCore: "gambatte", EmulatorJSCore: "gambatte", FolderName: "gbc", CoverAspect: "7:8", ColorTheme: "#5c1230", Generation: 5, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1998), UnitsSold: int64Ptr(49020000), Summary: strPtr("The Game Boy Color added a color screen to the Game Boy line while maintaining backward compatibility with the original library. It extended the Game Boy platform's dominance with titles like Pokemon Gold and Silver, The Legend of Zelda: Oracle games, and Wario Land 3."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "JAG", Name: "Atari Jaguar", Code: "jaguar", Extensions: ".j64,.jag", DefaultCore: "virtualjaguar", EmulatorJSCore: "virtualjaguar", FolderName: "atarijaguar", ColorTheme: "#1c1c1c", Generation: 5, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1993), UnitsSold: int64Ptr(250000), Summary: strPtr("The Atari Jaguar was marketed as the first 64-bit console, though its complex multi-chip architecture made it difficult to develop for. It was Atari's final home console, and despite titles like Alien vs Predator and Tempest 2000, its small library led to commercial failure."), Playable: true, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "VB", Name: "Virtual Boy", Code: "virtualboy", Extensions: ".vb,.vboy", DefaultCore: "beetle_vb", EmulatorJSCore: "beetle_vb", FolderName: "virtualboy", ColorTheme: "#1c1c1c", Generation: 5, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(1995), UnitsSold: int64Ptr(770000), Summary: strPtr("The Virtual Boy was Nintendo's experimental tabletop console that displayed stereoscopic 3D graphics in red and black. Designed by Game Boy creator Gunpei Yokoi, it was discontinued after less than a year due to poor sales caused by its uncomfortable design and monochromatic display."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "3DO", Name: "3DO", Code: "3do", Extensions: ".iso,.bin,.cue,.chd", DefaultCore: "opera", EmulatorJSCore: "opera", FolderName: "3do", ColorTheme: "#c0c0c0", Generation: 5, MakerCode: "panasonic", MediaCode: "cd-rom", ReleaseYear: intPtr(1993), UnitsSold: int64Ptr(2000000), Summary: strPtr("The 3DO Interactive Multiplayer was designed by EA founder Trip Hawkins and manufactured by Panasonic, LG, and Sanyo under an open licensing model. Its high launch price of $699 limited adoption despite impressive hardware and notable titles like Road Rash and Return Fire."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "NGP", Name: "Neo Geo Pocket / Color", Code: "ngp", Extensions: ".ngp,.ngc", DefaultCore: "beetle_ngp", EmulatorJSCore: "mednafen_ngp", FolderName: "ngp", CoverAspect: "1:1", ColorTheme: "#1a75bc", Generation: 5, MakerCode: "snk", MediaCode: "cartridge", ReleaseYear: intPtr(1998), UnitsSold: int64Ptr(2000000), Summary: strPtr("The Neo Geo Pocket, and its color successor the Neo Geo Pocket Color, was SNK's entry into the handheld market. Known for its excellent micro-switch joystick and strong fighting game library including SNK vs. Capcom: Match of the Millennium, it could not overcome the Game Boy Color's market dominance."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "WS", Name: "WonderSwan", Code: "wonderswan", Extensions: ".ws,.wsc", DefaultCore: "beetle_wswan", EmulatorJSCore: "mednafen_wswan", FolderName: "wonderswan", CoverAspect: "1:1", ColorTheme: "#4b0082", Generation: 5, MakerCode: "bandai", MediaCode: "cartridge", ReleaseYear: intPtr(1999), UnitsSold: int64Ptr(3500000), Summary: strPtr("The WonderSwan was designed by Gunpei Yokoi after leaving Nintendo and was sold exclusively in Japan. Its low price and excellent battery life attracted Square for exclusive Final Fantasy remakes, but the Game Boy Advance's arrival halted its momentum."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "32X", Name: "Sega 32X", Code: "32x", Extensions: ".32x", DefaultCore: "picodrive", EmulatorJSCore: "sega32x", FolderName: "sega32x", ColorTheme: "#1a1a1a", Generation: 5, MakerCode: "sega", MediaCode: "cartridge", ReleaseYear: intPtr(1994), UnitsSold: int64Ptr(665000), Summary: strPtr("The Sega 32X was an add-on for the Genesis designed to extend its lifespan with 32-bit capabilities. Released just months before the Saturn, it confused consumers and developers alike, becoming one of the most notable commercial failures in console hardware history."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PCFX", Name: "PC-FX", Code: "pcfx", Extensions: ".iso,.cue,.m3u", DefaultCore: "beetle_pcfx", EmulatorJSCore: "mednafen_pcfx", FolderName: "pcfx", ColorTheme: "#ff6600", Generation: 5, MakerCode: "nec", MediaCode: "cd-rom", ReleaseYear: intPtr(1994), UnitsSold: int64Ptr(400000), Summary: strPtr("The PC-FX was NEC's successor to the TurboGrafx-16, focusing on full-motion video and 2D graphics rather than competing in the 3D polygon race. Sold only in Japan, it failed to gain traction against the PlayStation and Saturn due to its lack of 3D capabilities and limited game library."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "ACD32", Name: "Amiga CD32", Code: "acd32", Extensions: ".iso,.cue,.bin,.chd", FolderName: "acd32", CoverAspect: "8:11", ColorTheme: "#c47d1a", Generation: 5, MakerCode: "commodore", MediaCode: "cd-rom", ReleaseYear: intPtr(1993), Summary: strPtr("The Amiga CD32 was the world's first 32-bit CD-ROM-based home console, built on the Amiga 1200 architecture. Commodore's bankruptcy in 1994 cut short its promising start, particularly in Europe where it had gained meaningful traction in its brief time on the market."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PS2", Name: "PlayStation 2", Code: "ps2", Extensions: ".iso,.bin,.cue,.chd,.m3u", DefaultCore: "play", FolderName: "ps2", ColorTheme: "#003087", Generation: 6, MakerCode: "sony", MediaCode: "dvd-rom", ReleaseYear: intPtr(2000), UnitsSold: int64Ptr(155000000), Summary: strPtr("The PlayStation 2 is the best-selling video game console of all time, with a library of over 4,000 games spanning every genre. Its built-in DVD player, backward compatibility with PS1 games, and landmark titles like Grand Theft Auto: San Andreas, Shadow of the Colossus, and Final Fantasy X made it a cultural phenomenon."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "DC", Name: "Dreamcast", Code: "dreamcast", Extensions: ".gdi,.cdi,.chd,.cue,.bin,.m3u", DefaultCore: "flycast", FolderName: "dreamcast", ColorTheme: "#c0c0c0", Generation: 6, MakerCode: "sega", MediaCode: "gd-rom", ReleaseYear: intPtr(1998), UnitsSold: int64Ptr(9130000), Summary: strPtr("The Dreamcast was Sega's final home console and the first of the sixth generation, featuring built-in modem support for online gaming. Despite critical acclaim and innovative titles like Shenmue, Jet Set Radio, and Sonic Adventure, it was unable to compete against the upcoming PlayStation 2 and was discontinued in 2001."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "GC", Name: "Nintendo GameCube", Code: "gamecube", Extensions: ".iso,.gcm,.gcz,.ciso,.rvz", DefaultCore: "dolphin", FolderName: "gc", CoverAspect: "1:1", ColorTheme: "#6f5fa6", Generation: 6, MakerCode: "nintendo", MediaCode: "dvd-rom", ReleaseYear: intPtr(2001), UnitsSold: int64Ptr(21740000), Summary: strPtr("The Nintendo GameCube used proprietary mini-DVDs and featured a distinctive compact design with a carrying handle. While it sold fewer units than the PS2 and Xbox, it hosted beloved exclusives like Super Smash Bros. Melee, Metroid Prime, and The Legend of Zelda: The Wind Waker."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "GBA", Name: "Game Boy Advance", Code: "gba", Extensions: ".gba", DefaultCore: "mgba", EmulatorJSCore: "mgba", FolderName: "gba", CoverAspect: "1:1", ColorTheme: "#2e17a3", Generation: 6, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(2001), UnitsSold: int64Ptr(81510000), Summary: strPtr("The Game Boy Advance brought 32-bit gaming to Nintendo's handheld line with graphics comparable to the SNES. Its impressive library included Pokemon Ruby and Sapphire, The Legend of Zelda: The Minish Cap, and Metroid Fusion, cementing Nintendo's dominance in portable gaming."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PKMN", Name: "Pokemon Mini", Code: "pokemonmini", Extensions: ".min", DefaultCore: "pokemini", FolderName: "pokemonmini", CoverAspect: "1:1", ColorTheme: "#ffcc00", Generation: 6, MakerCode: "nintendo", MediaCode: "cartridge", ReleaseYear: intPtr(2001), Summary: strPtr("The Pokemon Mini is the smallest cartridge-based game console ever produced by Nintendo. Designed as a novelty device tied to the Pokemon franchise, it featured a small monochrome screen, a rumble motor, and an infrared port for multiplayer, with a library of just ten games."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "XBOX", Name: "Xbox", Code: "xbox", Extensions: ".iso,.xbe", FolderName: "xbox", CoverAspect: "8:11", ColorTheme: "#107c10", Generation: 6, MakerCode: "microsoft", MediaCode: "dvd-rom", ReleaseYear: intPtr(2001), UnitsSold: int64Ptr(24000000), Summary: strPtr("The Xbox was Microsoft's first entry into the console market, featuring PC-derived hardware with a built-in hard drive and Ethernet port. Halo: Combat Evolved became its killer app and system seller, while Xbox Live pioneered unified online console gaming."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "WII", Name: "Nintendo Wii", Code: "wii", Extensions: ".iso,.wbfs,.gcz,.rvz,.ciso", DefaultCore: "dolphin", FolderName: "wii", CoverAspect: "8:11", ColorTheme: "#c0c0c0", Generation: 7, MakerCode: "nintendo", MediaCode: "dvd-rom", ReleaseYear: intPtr(2006), UnitsSold: int64Ptr(101630000), Summary: strPtr("The Wii revolutionized gaming with its motion-sensing Wii Remote controller, attracting millions of non-traditional gamers. Wii Sports became a cultural phenomenon, and the console outsold both the PS3 and Xbox 360, proving that innovative gameplay could triumph over raw processing power."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "PS3", Name: "PlayStation 3", Code: "ps3", Extensions: ".iso,.bin,.pkg", FolderName: "ps3", CoverAspect: "8:11", ColorTheme: "#003087", Generation: 7, MakerCode: "sony", MediaCode: "blu-ray", ReleaseYear: intPtr(2006), UnitsSold: int64Ptr(87400000), Summary: strPtr("The PlayStation 3 was the first console with a built-in Blu-ray player and featured the powerful Cell processor co-developed with IBM. Despite a rocky launch at a premium price, it recovered with critically acclaimed exclusives like The Last of Us, Uncharted 2, and free online multiplayer."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "X360", Name: "Xbox 360", Code: "x360", Extensions: ".iso,.xex,.god", FolderName: "xbox360", CoverAspect: "8:11", ColorTheme: "#107c10", Generation: 7, MakerCode: "microsoft", MediaCode: "dvd-rom", ReleaseYear: intPtr(2005), UnitsSold: int64Ptr(84700000), Summary: strPtr("The Xbox 360 launched a year ahead of its competitors and established Xbox Live as the premier online gaming service. Its achievement system, party chat, and blockbuster exclusives like Gears of War and Halo 3 defined the era of connected console gaming."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "PSP", Name: "PlayStation Portable", Code: "psp", Extensions: ".iso,.cso,.chd", DefaultCore: "ppsspp", EmulatorJSCore: "ppsspp", FolderName: "psp", ColorTheme: "#455a8a", Generation: 7, MakerCode: "sony", MediaCode: "umd", ReleaseYear: intPtr(2004), UnitsSold: int64Ptr(80000000), Summary: strPtr("The PlayStation Portable was Sony's first handheld console, featuring a widescreen display and near-PS2 quality graphics. Its UMD optical disc format enabled console-quality games like God of War: Chains of Olympus, Monster Hunter Freedom Unite, and Crisis Core: Final Fantasy VII."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "NDS", Name: "Nintendo DS", Code: "nds", Extensions: ".nds", DefaultCore: "desmume", EmulatorJSCore: "desmume", FolderName: "nds", CoverAspect: "10:9", ColorTheme: "#b0b0b0", Generation: 7, MakerCode: "nintendo", MediaCode: "game-card", ReleaseYear: intPtr(2004), UnitsSold: int64Ptr(154020000), Summary: strPtr("The Nintendo DS introduced dual screens and touch input to handheld gaming, creating entirely new gameplay possibilities. As the second best-selling console ever, it reached massive audiences with titles like Brain Age, Nintendogs, New Super Mario Bros., and Pokemon Diamond and Pearl."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "WIIU", Name: "Nintendo Wii U", Code: "wiiu", Extensions: ".rpx,.wud,.wux", FolderName: "wiiu", CoverAspect: "8:11", ColorTheme: "#009ac7", Generation: 8, MakerCode: "nintendo", MediaCode: "disc", ReleaseYear: intPtr(2012), UnitsSold: int64Ptr(13560000), Summary: strPtr("The Wii U featured an innovative GamePad controller with a built-in touchscreen for asymmetric gameplay and off-TV play. Despite underperforming commercially due to confused marketing and slow software output, it produced excellent first-party titles like Super Mario 3D World, Splatoon, and Super Smash Bros. for Wii U."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "VITA", Name: "PlayStation Vita", Code: "vita", Extensions: ".vpk,.mai,.zip", FolderName: "psvita", CoverAspect: "8:11", ColorTheme: "#003087", Generation: 8, MakerCode: "sony", MediaCode: "game-card", ReleaseYear: intPtr(2011), UnitsSold: int64Ptr(15900000), Summary: strPtr("The PlayStation Vita was Sony's second handheld console, featuring a 5-inch OLED touchscreen, rear touchpad, and dual analog sticks. Despite powerful hardware capable of near-PS3 quality visuals, it struggled against mobile gaming competition, though it found a devoted audience for its strong library of JRPGs, indie games, and remote play functionality."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyMedium},
	{Abbreviation: "PS4", Name: "PlayStation 4", Code: "ps4", Extensions: ".pkg", FolderName: "ps4", CoverAspect: "8:11", ColorTheme: "#003087", Generation: 8, MakerCode: "sony", MediaCode: "blu-ray", ReleaseYear: intPtr(2013), UnitsSold: int64Ptr(117200000), Summary: strPtr("The PlayStation 4 focused on being a developer-friendly gaming powerhouse with a standard x86 architecture. Its massive install base and acclaimed exclusives like God of War, Horizon Zero Dawn, and Marvel's Spider-Man made it the dominant console of the eighth generation."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "XONE", Name: "Xbox One", Code: "xone", Extensions: ".xvd", FolderName: "xboxone", CoverAspect: "8:11", ColorTheme: "#107c10", Generation: 8, MakerCode: "microsoft", MediaCode: "blu-ray", ReleaseYear: intPtr(2013), UnitsSold: int64Ptr(51000000), Summary: strPtr("The Xbox One initially focused on being an all-in-one entertainment hub before pivoting back to games. Microsoft introduced backward compatibility and the Xbox Game Pass subscription service, which became the most significant shift in console business models since digital distribution."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "3DS", Name: "Nintendo 3DS", Code: "3ds", Extensions: ".3ds,.cci,.cia", DefaultCore: "azahar", FolderName: "n3ds", ColorTheme: "#ce181e", Generation: 8, MakerCode: "nintendo", MediaCode: "game-card", ReleaseYear: intPtr(2011), UnitsSold: int64Ptr(75940000), Summary: strPtr("The Nintendo 3DS delivered glasses-free stereoscopic 3D visuals and featured backward compatibility with DS games. Its StreetPass social features and strong library including Pokemon X/Y, Fire Emblem Awakening, and Animal Crossing: New Leaf made it Nintendo's most successful dedicated handheld after the original DS family."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "NSW", Name: "Nintendo Switch", Code: "nsw", Extensions: ".nsp,.xci", FolderName: "switch", CoverAspect: "8:11", ColorTheme: "#e60012", Generation: 9, MakerCode: "nintendo", MediaCode: "game-card", ReleaseYear: intPtr(2017), UnitsSold: int64Ptr(143420000), Summary: strPtr("The Nintendo Switch combined home console and portable gaming into a single hybrid device with detachable Joy-Con controllers. Its versatile design and critically acclaimed games like The Legend of Zelda: Breath of the Wild, Animal Crossing: New Horizons, and Mario Kart 8 Deluxe made it one of the best-selling consoles in history."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "PS5", Name: "PlayStation 5", Code: "ps5", Extensions: ".pkg", FolderName: "ps5", CoverAspect: "8:11", ColorTheme: "#003087", Generation: 9, MakerCode: "sony", MediaCode: "blu-ray", ReleaseYear: intPtr(2020), UnitsSold: int64Ptr(67000000), Summary: strPtr("The PlayStation 5 introduced an ultra-fast custom SSD that virtually eliminated loading times and featured the innovative DualSense controller with haptic feedback and adaptive triggers. Exclusives like Demon's Souls, Ratchet & Clank: Rift Apart, and Astro Bot showcase its next-generation capabilities."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "XSX", Name: "Xbox Series", Code: "xsx", Extensions: ".xvd", FolderName: "xboxseries", CoverAspect: "8:11", ColorTheme: "#107c10", Generation: 9, MakerCode: "microsoft", MediaCode: "digital", ReleaseYear: intPtr(2020), UnitsSold: int64Ptr(21000000), Summary: strPtr("The Xbox Series X/S continued Microsoft's shift toward a service-based model, with Game Pass at its core. The Series X offered the most powerful console hardware at launch, while the disc-less Series S provided an affordable entry point for next-gen gaming."), Playable: false, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicyLarge},
	{Abbreviation: "A26", Name: "Atari 2600", Code: "a26", Extensions: ".a26,.bin", DefaultCore: "stella", EmulatorJSCore: "stella2014", FolderName: "atari2600", ColorTheme: "#8b4513", Generation: 2, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1977), UnitsSold: int64Ptr(30000000), Summary: strPtr("The Atari 2600 popularized microprocessor-based home gaming and became the dominant console of the late 1970s and early 1980s. Its massive library of over 500 games helped establish video gaming as a mainstream entertainment medium, despite the infamous 1983 market crash."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "A52", Name: "Atari 5200", Code: "a52", Extensions: ".a52,.bin", DefaultCore: "atari800", FolderName: "atari5200", ColorTheme: "#1c1c1c", Generation: 2, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1982), UnitsSold: int64Ptr(1000000), Summary: strPtr("The Atari 5200 was Atari's successor to the 2600, featuring improved graphics and analog joystick controllers. Despite its technical improvements, it struggled commercially due to controller reliability issues and competition from the ColecoVision."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "CV", Name: "ColecoVision", Code: "colecovision", Extensions: ".col,.rom", DefaultCore: "gearcoleco", EmulatorJSCore: "gearcoleco", FolderName: "colecovision", ColorTheme: "#1565c0", Generation: 2, MakerCode: "coleco", MediaCode: "cartridge", ReleaseYear: intPtr(1982), UnitsSold: int64Ptr(2000000), Summary: strPtr("The ColecoVision offered near-arcade-quality graphics and was bundled with Donkey Kong, making it a strong competitor in the early 1980s. Its expansion module allowed backward compatibility with Atari 2600 games, but the 1983 video game crash cut its lifespan short."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "CHAF", Name: "Fairchild Channel F", Code: "channelf", Extensions: ".bin,.chf", DefaultCore: "freechaf", FolderName: "channelf", ColorTheme: "#cc6600", Generation: 2, MakerCode: "fairchild", MediaCode: "cartridge", ReleaseYear: intPtr(1976), UnitsSold: int64Ptr(250000), Summary: strPtr("The Fairchild Channel F was the first home video game console to use programmable ROM cartridges, predating the Atari 2600 by a year. While commercially overshadowed by Atari, it pioneered the concept of interchangeable game cartridges that defined the industry for decades."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "O2", Name: "Magnavox Odyssey 2", Code: "odyssey2", Extensions: ".bin,.o2", DefaultCore: "o2em", FolderName: "odyssey2", ColorTheme: "#b8860b", Generation: 2, MakerCode: "magnavox", MediaCode: "cartridge", ReleaseYear: intPtr(1978), UnitsSold: int64Ptr(2000000), Summary: strPtr("The Magnavox Odyssey 2, known as the Philips Videopac G7000 in Europe, featured a built-in membrane keyboard that set it apart from competitors. Its unique combination of gaming and limited computing capabilities made it popular in Europe, though it struggled against the Atari 2600 in North America."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "INTV", Name: "Mattel Intellivision", Code: "intellivision", Extensions: ".int,.bin,.rom", DefaultCore: "freeintv", FolderName: "intellivision", ColorTheme: "#c47d1a", Generation: 2, MakerCode: "mattel", MediaCode: "cartridge", ReleaseYear: intPtr(1979), UnitsSold: int64Ptr(3000000), Summary: strPtr("The Mattel Intellivision was the first console to pose a serious challenge to Atari's dominance, featuring superior graphics and distinctive disc-shaped controllers with numeric keypads. Its sports games were particularly acclaimed, and it introduced the concept of downloadable content through the PlayCable service."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "VEC", Name: "GCE Vectrex", Code: "vectrex", Extensions: ".bin,.vec", DefaultCore: "vecx", FolderName: "vectrex", ColorTheme: "#333333", Generation: 2, MakerCode: "gce", MediaCode: "cartridge", ReleaseYear: intPtr(1982), Summary: strPtr("The GCE Vectrex was unique among home consoles for its built-in vector display monitor, producing crisp line graphics similar to arcade games like Asteroids and Tempest. Despite critical acclaim and innovative accessories including a 3D imager, it was discontinued after the 1983 video game crash."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "GW", Name: "Nintendo Game & Watch", Code: "gw", Extensions: ".mgw", DefaultCore: "gw", FolderName: "gameandwatch", CoverAspect: "1:1", ColorTheme: "#c0392b", Generation: 1, MakerCode: "nintendo", MediaCode: "digital", ReleaseYear: intPtr(1980), UnitsSold: int64Ptr(43400000), Summary: strPtr("Nintendo Game & Watch was a line of handheld electronic games created by Gunpei Yokoi, featuring LCD screens with fixed game graphics. Spanning 59 models from 1980 to 1991, they introduced the cross-shaped directional pad that became standard on all subsequent Nintendo controllers."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "A800", Name: "Atari 8-bit", Code: "a800", Extensions: ".a52,.atr,.atx,.bas,.bin,.car,.cas,.com,.rom,.xex,.xfd", DefaultCore: "atari800", FolderName: "atari800", ColorTheme: "#1c1c1c", Generation: 100, MakerCode: "atari", MediaCode: "cartridge", ReleaseYear: intPtr(1979), Summary: strPtr("The Atari 8-bit family, starting with the Atari 400 and 800, featured custom chips designed by Jay Miner that provided advanced graphics and sound capabilities for their era. The line evolved through the XL and XE series, building a strong library of games and creative software that influenced a generation of programmers and game designers."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "ATARIST", Name: "Atari ST", Code: "atarist", Extensions: ".st,.stx,.msa,.dim,.m3u", DefaultCore: "hatari", FolderName: "atarist", ColorTheme: "#1c1c1c", Generation: 100, MakerCode: "atari", MediaCode: "floppy-disk", ReleaseYear: intPtr(1985), Summary: strPtr("The Atari ST was a popular 16/32-bit home computer that rivaled the Commodore Amiga, particularly in Europe. Its built-in MIDI ports made it the standard platform for music production throughout the late 1980s and early 1990s, while also hosting a strong library of games and creative software."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "C64", Name: "Commodore 64", Code: "c64", Extensions: ".d64,.t64,.prg,.crt,.tap", DefaultCore: "vice_x64sc", EmulatorJSCore: "vice_x64sc", FolderName: "c64", ColorTheme: "#c2a878", Generation: 100, MakerCode: "commodore", MediaCode: "floppy-disk", ReleaseYear: intPtr(1982), UnitsSold: int64Ptr(17000000), Summary: strPtr("The Commodore 64 is the best-selling single personal computer model of all time, renowned for its advanced sound chip (SID) and capable graphics. Its affordable price and massive software library of over 10,000 titles made it a cornerstone of 1980s home computing and gaming culture."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "C128", Name: "Commodore 128", Code: "c128", Extensions: ".d64,.d71,.d81,.t64,.prg,.crt", DefaultCore: "vice_x128", EmulatorJSCore: "vice_x128", FolderName: "c128", ColorTheme: "#6c5eb5", Generation: 100, MakerCode: "commodore", MediaCode: "floppy-disk", ReleaseYear: intPtr(1985), UnitsSold: int64Ptr(4000000), Summary: strPtr("The Commodore 128 was the successor to the C64, featuring three operating modes including full C64 backward compatibility and a CP/M mode. While technically superior to its predecessor, most users simply ran it in C64 mode, and it never achieved the same cultural impact."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PET", Name: "Commodore PET", Code: "pet", Extensions: ".prg,.d64,.t64", DefaultCore: "vice_xpet", EmulatorJSCore: "vice_xpet", FolderName: "pet", ColorTheme: "#6c5eb5", Generation: 100, MakerCode: "commodore", MediaCode: "cartridge", ReleaseYear: intPtr(1977), Summary: strPtr("The Commodore PET was one of the first mass-produced personal computers, featuring an all-in-one design with built-in monitor and cassette drive. Primarily used in education and business, it established Commodore as a major force in the personal computer industry."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "PLUS4", Name: "Commodore Plus/4", Code: "plus4", Extensions: ".prg,.d64,.t64", DefaultCore: "vice_xplus4", EmulatorJSCore: "vice_xplus4", FolderName: "plus4", ColorTheme: "#c47d1a", Generation: 100, MakerCode: "commodore", MediaCode: "cartridge", ReleaseYear: intPtr(1984), Summary: strPtr("The Commodore Plus/4 was positioned as a business-oriented home computer with built-in productivity software. Despite improved BASIC and graphics capabilities over the C64, its incompatibility with the C64's software library and lack of hardware sprites limited its appeal to gamers and hobbyists."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "VIC20", Name: "Commodore VIC-20", Code: "vic20", Extensions: ".prg,.d64,.t64,.crt", DefaultCore: "vice_xvic", EmulatorJSCore: "vice_xvic", FolderName: "vic20", ColorTheme: "#6c5eb5", Generation: 100, MakerCode: "commodore", MediaCode: "cartridge", ReleaseYear: intPtr(1980), UnitsSold: int64Ptr(2500000), Summary: strPtr("The Commodore VIC-20 was one of the first computers to sell over a million units, priced affordably at under $300. While limited to 5KB of RAM, it introduced an entire generation to home computing and programming, serving as a stepping stone to the legendary Commodore 64."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "AMIGA", Name: "Commodore Amiga", Code: "amiga", Extensions: ".adf,.hdf,.lha,.dms,.zip", DefaultCore: "puae", EmulatorJSCore: "puae", FolderName: "amiga", ColorTheme: "#c47d1a", Generation: 100, MakerCode: "commodore", MediaCode: "floppy-disk", ReleaseYear: intPtr(1985), Summary: strPtr("The Commodore Amiga was a revolutionary multimedia computer with custom chips for graphics, sound, and I/O that were years ahead of competing platforms. Its pre-emptive multitasking operating system and powerful capabilities made it the platform of choice for video production, music, and gaming in Europe throughout the late 1980s and early 1990s."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "ADEMO", Name: "Amiga Demos", Code: "ademo", Extensions: ".adf,.hdf,.lha,.dms,.zip", DefaultCore: "puae", EmulatorJSCore: "puae", FolderName: "amiga-demos", ColorTheme: "#c47d1a", Tag: strPtr("Demos"), Generation: 100, MakerCode: "commodore", MediaCode: "floppy-disk", Summary: strPtr("The Amiga demo scene was one of the most vibrant creative computing communities, pushing the Amiga's custom hardware to produce stunning audiovisual demonstrations. Originating in the late 1980s, it became a breeding ground for future game developers, digital artists, and musicians."), Playable: true, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "DOS", Name: "DOS", Code: "dos", Extensions: ".zip,.dosz,.conf", DefaultCore: "dosbox_pure", EmulatorJSCore: "dosbox_pure", FolderName: "dos", ColorTheme: "#000000", Generation: 100, MakerCode: "ibm", MediaCode: "floppy-disk", ReleaseYear: intPtr(1981), Summary: strPtr("DOS, the Disk Operating System for IBM PC compatibles, became the dominant personal computing platform through the 1980s and early 1990s. Its open architecture spawned the PC gaming industry, with classic titles like Doom, Commander Keen, and Civilization defining entire genres."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "DDEMO", Name: "DOS Demos", Code: "ddemo", Extensions: ".zip,.dosz,.conf", DefaultCore: "dosbox_pure", EmulatorJSCore: "dosbox_pure", FolderName: "dos-demos", ColorTheme: "#333333", Tag: strPtr("Demos"), Generation: 100, MakerCode: "various", MediaCode: "digital", Summary: strPtr("The DOS demo scene produced creative real-time audiovisual programs that showcased programming skill and artistic expression on IBM PC compatibles. Demos like Second Reality by Future Crew became legendary, and the scene continues to thrive at events like Assembly and Revision."), Playable: true, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "MSX1", Name: "MSX", Code: "msx1", Extensions: ".rom,.mx1,.dsk,.cas", DefaultCore: "bluemsx", FolderName: "msx1", ColorTheme: "#4a86c8", Generation: 100, MakerCode: "microsoft", MediaCode: "cartridge", ReleaseYear: intPtr(1983), Summary: strPtr("MSX was a standardized home computer architecture initiated by Microsoft and ASCII Corporation, adopted by manufacturers across Japan, South Korea, and Europe. It became a major gaming platform in Japan, launching the Metal Gear and Bomberman franchises."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "MSX2", Name: "MSX2", Code: "msx2", Extensions: ".rom,.mx2,.dsk,.cas", DefaultCore: "bluemsx", FolderName: "msx2", ColorTheme: "#4a86c8", Generation: 100, MakerCode: "microsoft", MediaCode: "cartridge", ReleaseYear: intPtr(1985), Summary: strPtr("MSX2 was the second generation of the MSX standard, offering improved graphics with more colors and hardware scrolling. It saw continued success in Japan and the Netherlands, with notable titles including Metal Gear 2: Solid Snake and Vampire Killer."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "ZXS", Name: "Sinclair ZX Spectrum", Extensions: ".tap,.tzx,.z80,.sna,.szx,.dsk,.trd,.scl,.mgt", DefaultCore: "fuse", FolderName: "zxspectrum", ColorTheme: "#cc0000", Generation: 100, Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "CPC", Name: "Amstrad CPC", Extensions: ".dsk,.sna,.tap,.cdt,.voc,.cpr,.m3u", DefaultCore: "cap32", FolderName: "amstradcpc", ColorTheme: "#1f3864", Generation: 100, Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "X68K", Name: "Sharp X68000", Extensions: ".dim,.img,.d88,.88d,.hdm,.hdf,.m3u", DefaultCore: "px68k", FolderName: "x68000", ColorTheme: "#666666", Generation: 100, Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "ARCADE", Name: "Arcade", Code: "arcade", Extensions: ".zip", DefaultCore: "mame2003_plus", EmulatorJSCore: "fbneo", FolderName: "arcade", ColorTheme: "#0a8d7b", Generation: 101, MakerCode: "various", MediaCode: "arcade-board", ReleaseYear: intPtr(1971), Summary: strPtr("Arcade games have been a cornerstone of the video game industry since Computer Space in 1971 and Pong in 1972. From the golden age of Space Invaders and Pac-Man to modern fighting and rhythm games, arcades pioneered nearly every major gaming genre and remain a vibrant part of gaming culture worldwide."), Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "SCUMMVM", Name: "ScummVM", Code: "scummvm", Extensions: ".scummvm", DefaultCore: "scummvm", FolderName: "scummvm", CoverAspect: "5:7", ColorTheme: "#6b8e23", Generation: 100, MakerCode: "various", MediaCode: "digital", Summary: strPtr("ScummVM is a collection of game engine reimplementations that allows classic point-and-click adventure games to run on modern hardware. Originally created to run LucasArts SCUMM games like Monkey Island and Day of the Tentacle, it now supports hundreds of adventure games from numerous publishers."), Playable: true, SaveStateSupport: false, SaveStatePolicy: SaveStatePolicySmall},
	{Abbreviation: "TIC80", Name: "TIC-80", Extensions: ".tic", DefaultCore: "tic80", FolderName: "tic80", CoverAspect: "1:1", ColorTheme: "#1a1a2e", Generation: 102, Playable: true, SaveStateSupport: true, SaveStatePolicy: SaveStatePolicySmall},
}

// toConsole builds the database row for this spec. It carries only the
// fields SeedConsoles persists directly; the maker/media foreign keys are
// applied by SeedConsoleMetadata, and the intrinsic-fact fields
// (CoverAspect, Generation) are not stored at all — they are derived from
// the registry on load via Console.AfterFind (#1443).
func (s ConsoleSpec) toConsole() Console {
	return Console{
		Abbreviation:     s.Abbreviation,
		Extensions:       s.Extensions,
		DefaultCore:      s.DefaultCore,
		EmulatorJSCore:   s.EmulatorJSCore,
		FolderName:       s.FolderName,
		ColorTheme:       s.ColorTheme,
		SaveStateSupport: s.SaveStateSupport,
		SaveStatePolicy:  s.SaveStatePolicy,
		Playable:         s.Playable,
	}
}

// DefaultCoverAspect is the fallback cover-art aspect for consoles whose
// registry entry declares none. Mirrors the historical column default.
const DefaultCoverAspect = "3:4"

// ConsoleCoverAspect returns a console's cover-art aspect string from the
// registry, matched case-insensitively on abbreviation and falling back to
// DefaultCoverAspect. Used by both Console.AfterFind and the raw-SQL read
// paths that can't go through the model hook.
func ConsoleCoverAspect(abbr string) string {
	if s, ok := ConsoleSpecByAbbreviation(strings.ToUpper(abbr)); ok && s.CoverAspect != "" {
		return s.CoverAspect
	}
	return DefaultCoverAspect
}

// ConsoleName returns a console's display name from the registry, matched
// case-insensitively on abbreviation. Falls back to the abbreviation itself
// when no registry entry exists (only synthetic test consoles). Used by
// Console.AfterFind and the raw-SQL read paths that bypass the model hook.
func ConsoleName(abbr string) string {
	if s, ok := ConsoleSpecByAbbreviation(strings.ToUpper(abbr)); ok {
		return s.Name
	}
	return abbr
}

// ConsoleSpecByAbbreviation returns the registry entry for an abbreviation
// (e.g. "NES"), or false if none is defined.
func ConsoleSpecByAbbreviation(abbr string) (ConsoleSpec, bool) {
	for _, s := range consoleRegistry {
		if s.Abbreviation == abbr {
			return s, true
		}
	}
	return ConsoleSpec{}, false
}

// ConsoleSpecByCode returns the registry entry for a canonical code (e.g.
// "nes"), or false if none is defined. Codes are unique; entries with an
// empty code are never matched.
func ConsoleSpecByCode(code string) (ConsoleSpec, bool) {
	if code == "" {
		return ConsoleSpec{}, false
	}
	for _, s := range consoleRegistry {
		if s.Code == code {
			return s, true
		}
	}
	return ConsoleSpec{}, false
}

// ConsoleRegistry returns the full console catalog in seed order.
func ConsoleRegistry() []ConsoleSpec {
	return consoleRegistry
}
